### ISSUE TITLE
测试固件v006

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#1]
#### WAN 口 TTYD 能否访问

* 默认防火墙 WAN 口，如果非 PPPoE 是接受的状态，应该能访问
* 方便小白操作，或者作为独立 NAS 的时候，可以用 WAN 口 IP 访问，不用接电脑的网线操作，省事

#### PPPoE 之后，防火墙是否关闭

因为 PPPoE 可能是公网 IP，防火墙要自动关掉

#### iStore 全部插件的安装

估计这里有很多问题，需要一个一个解决

#### iStore 的插件备份跟恢复

轻量备份，全量备份测试

#### iStore 的离线安装包测试

TODO，需要提供各种离线包的测试方法

#### Docker 测试

主要是 Docker 镜像是否能自动把外部的硬件，挂载到 Docker 里面，方便小白Docker里面共享外部的硬盘，减少做磁盘映射的操作

#### 下载测试

如果不小心把下载路径指定到 /mnt/xxx/aria2，而且硬盘掉了，会不会把根目录整满了

#### 遗留 BUG 确认

- [x] 重启之后偶尔变成英文界面，还无法选择中文
- [x] 偶尔会出现 403 错误，导致用户必须清空浏览器缓存才能登录

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3951/1
