### ISSUE TITLE
端口转发的nat环回无效

### ISSUE THREAD

**Issue by gzxiexl** [linkease/istoreos#10]
0411最新版实测端口转发的nat环回无效

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by cnfjice** [comment]
0415的版本也不能。。。

**Comment by zwtocn** [comment]
Openwrt有效 其他均无效

**Comment by jannson** [comment]
请方便提供下，你是如何测试的么？我让我们同事跟着你的方法测试下

**Comment by gzxiexl** [comment]
我的是wan的6443转发到10.0.0.254（nas）的6443，外网测试了转发有效，但是在内网测试转发无效

**Comment by cnfjice** [comment]
安装openclash后，端口映射的ip会变成内网ip，当然，依然无法环回。

**Comment by cnfjice** [comment]
> 请方便提供下，你是如何测试的么？我让我们同事跟着你的方法测试下

动态dns里没有阿里云dns，自己安装了一个，添加了2条动态dns，一条花生壳，一条阿里云dns，ip获取正常。内网用域名无法访问，外网正常。。。
[ddns-scripts_aliyun_1.0.2-1_all.zip](https://github.com/linkease/istoreos/files/8501284/ddns-scripts_aliyun_1.0.2-1_all.zip)

**Comment by jannson** [comment]
好的。我们进行测试。

**Comment by jannson** [comment]
应该是 Docker 导致，我们看看如何修复。

**Comment by jannson** [comment]
下个版本这个问题应该能修复，明天固件出来我亲自测试下。

**Comment by jannson** [comment]
已经修复，请测试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3928/1
