### ISSUE TITLE
挂载分区丢失

### ISSUE THREAD

**Issue by coxlxd** [linkease/istoreos#100]
SSD，128G
除去tmp overlay 后挂载sda3每次重启都丢失。
另外更是无法将overlay扩容。
重启必定失效。

**Comment by jannson** [comment]
overlay 扩容现在是官方默认行为。我们后续版本为了保证插件能升级后不丢，会改动这里。到时候会支持一键扩容以及沙箱模式的能力。请等待。

**Comment by coxlxd** [comment]
其实我现在着急的是挂载sda3每次重启都丢失问题
导致不敢轻易重启，重启必定要再手动挂载，更不敢设置定时重启了

**Comment by jannson** [comment]
你是 overlay 丢失，还是挂载为存储丢失？你用首页挂载看看。。。挂载只要存到了系统中，是不会丢失的

**Comment by coxlxd** [comment]
今天因为停电又重启一次，之前挂载分区又丢了。
用首页那个菜单挂载，虽然我手工设置/mnt/sda3，但是还是被改成/mnt/data_sda3去了
无奈只好再进系统菜单
 手动删除/mnt/data_sda3挂载，手动勾选原来/mnt/sda3
（之前挂载分区，有用过ssh登录命令方式，在系统那边磁盘管理那手动加载等多种都是重启后sda3丢了）
检查发现插件基本都正常，就是docker中所有内容都丢了，配置容器什么都不见了。

**Comment by jannson** [comment]
我们故意改成 /mnt/data_sda3 的，因为系统老是把不同的硬盘分区搞冲突，所以只要是我们首页格式化的，就会切换为 data 开头。

如果是你手动挂载，用命令行哈的，不符合 openwrt 标准肯定得丢。

docker 你得重新切换到新的硬盘位置的路径。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3686/1
