### ISSUE TITLE
请问softether vpn怎么调呢？

### ISSUE THREAD

**Issue by Blacklw** [linkease/istoreos#101]
我在istoreos的软件包里面安装了几个softether vpn5的软件，然后在server manager里面调好了设置，并且在流量规则里面建立了对应端口，但是在测试拨号的时候会提示服务器没有回应，这个问题应该怎么调呢？
![1651489698(1)](https://user-images.githubusercontent.com/75933358/166224959-ae5b532d-9454-40fa-98b0-fe1641af9cf7.jpg)
![1651489708(1)](https://user-images.githubusercontent.com/75933358/166224979-d96f6c93-e0d5-484a-8d16-ed192c1e06a3.jpg)
![1651489678(1)](https://user-images.githubusercontent.com/75933358/166225004-c3f30c0b-e77c-45bb-8c2b-262d93954f25.png)
![1651489716(1)](https://user-images.githubusercontent.com/75933358/166225017-c79ae173-5902-45d1-bef5-8c89c2f9c92c.jpg)

**Comment by jannson** [comment]
这个我们来测试下哈。我放到待确认问题里面。

**Comment by fencatn** [comment]
防火墙需开放992 1194 5555端口，同时需要在命令行确认下 netstat -netlp | grep vpnserver 是否能看到这3个监听端口

**Comment by jannson** [comment]
经过确认，这个不是问题。可能你设置的防火墙问题。

**Comment by Blacklw** [comment]
> 经过确认，这个不是问题。可能你设置的防火墙问题。

你好，我防火墙里面试过改几次不同的配置都不行，能给我看看您的设置吗？麻烦您了。另外我连接的是L2TP使用共享密钥去连接的。

**Comment by Blacklw** [comment]
> 经过确认，这个不是问题。可能你设置的防火墙问题。

你好，我防火墙里面试过改3次不同的配置都不行，能给我看看您的设置吗？麻烦您了。另外我连接的是L2TP使用共享密钥去连接的。以下是我试过的配置组合
![1651829153](https://user-images.githubusercontent.com/75933358/167105229-55e95cf6-f2c0-48e9-9ccf-7473652499ca.jpg)
![1651829153](https://user-images.githubusercontent.com/75933358/167105254-d7c932f0-74bd-451e-a5b5-7a75582d618d.png)
![1651829153(1)](https://user-images.githubusercontent.com/75933358/167105283-0387d663-3944-4926-a45b-ae15cca48d34.jpg)

再补充几张我配置过与关于softether vpn的配置
![image](https://user-images.githubusercontent.com/75933358/167105457-1b0ad7e8-e8f8-494c-8bf5-41e13b0cb912.png)
![image](https://user-images.githubusercontent.com/75933358/167105577-875afc66-dd68-4b4d-a840-c6439e3980ce.png)

还有就是和openwrt和merlin配置softether vpn的时候比较，istore在创建本地网桥的时候会多一个说明出来，我不知道是不是和这个有关系
![image](https://user-images.githubusercontent.com/75933358/167106195-72412f06-e48b-45be-8156-0960412c89d2.png)

**Comment by Blacklw** [comment]
> 防火墙需开放992 1194 5555端口，同时需要在命令行确认下 netstat -netlp | grep vpnserver 是否能看到这3个监听端口

您说的我试过了，也确定端口是有监听状态的，但是还是一样的状态。
![image](https://user-images.githubusercontent.com/75933358/167106943-3a630dac-a5ef-442e-800f-fc801ea8fd88.png)

**Comment by fencatn** [comment]
你用电脑拨下VPN有没有什么报错，如果到不了验证用户名密码那一步，说明防火墙设置有问题，如果提示验证失败那很可能是SOFTETHER设置的问题。
网上找了个攻略你参考下呢https://www.iloft.xyz/archives/softether-l2tp-openwrt.html 你也可以搜下视频，网上很多的。
最容易出错的地方，一个就是VPN网桥，一个就是防火墙

**Comment by Blacklw** [comment]
> 你用电脑拨下VPN有没有什么报错，如果到不了验证用户名密码那一步，说明防火墙设置有问题，如果提示验证失败那很可能是SOFTETHER设置的问题。 网上找了个攻略你参考下呢https://www.iloft.xyz/archives/softether-l2tp-openwrt.html 你也可以搜下视频，网上很多的。 最容易出错的地方，一个就是VPN网桥，一个就是防火墙

![image](https://user-images.githubusercontent.com/75933358/168851936-9272b7a6-17a7-4226-b24a-34a80bd85b37.png)
这个图片就是报错额，我也不知道什么原因，最后我找到的解决办法是不装softethervpn5的所有服务和依赖，就单纯安装softethervpn和相关依赖，其它设置完全一样的，就好了，能连接上

**Comment by soulofhan** [comment]
Blacklw，你好，你的istore能使用softether作用服务端组建虚拟局域网吗？请问下需要安装那些软件包以及进行哪些设置？谢谢
![image](https://github.com/istoreos/istoreos/assets/23116292/374f034b-5d50-4cd5-a2a1-432abf996a89)
在软件包里搜出来的是这些，还有个4.8的版本，这部分软件需要装哪些

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3684/1
