### ISSUE TITLE
动态 DNS服务商里没有Cloudflare

### ISSUE THREAD

**Issue by ybml2019** [linkease/istoreos#102]
动态 DNS服务商里没有Cloudflare，麻烦修复下，谢谢

**Comment by diannei** [comment]
可以自己安装，在软件包里搜索ddns-scripts-cloudflare

**Comment by jannson** [comment]
收到，我们作为下一期的固件功能加进去。

**Comment by jannson** [comment]
https://openwrt.org/packages/pkgdata_owrt18_6/ddns-scripts_cloudflare.com-v4

**Comment by jannson** [comment]
最新版本已经支持。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3682/1
