### ISSUE TITLE
需要用到子接口桥接，如何启用

### ISSUE THREAD

**Issue by diannei** [linkease/istoreos#103]
第一次使用istore，昨天安装的最新版本，在接口配置里没有找到物理设置选项，怎么启用桥接接口呢？

**Comment by genesis-lua** [comment]
br-lan那个就是桥接设备啊，将端口加进去就是桥接的

**Comment by jannson** [comment]
@genesis-lua 感谢你的热心，考虑加我们群，私信我，就说是 genesis-lua。有礼物相送。。。

**Comment by diannei** [comment]
@genesis-lua 我不知道是不是我配置错了，之前用的openwrt按照网上的上海电信sdn iptv配置，添加eth0、1子接口51、85，接口桥接没有任何问题。前几天安装istoreos，接口配置页面有些变化，我尝试了在接口--设备里新建了4个子接口eth0.51 eth0.85 eth1.51 eth1.85, 2个网桥br-IPTV51绑定eth0.51 eth1.51, br-IPTV85绑定eth0.85 eth1.85。全部完成后到接口--接口中添加新接口，分别绑定这两个网桥，报错”错误: 未知错误（DEVICE_CLAIM_FAILED）“

**Comment by minwe** [comment]
@dymasch 搞定没有？我也是这错误

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3679/1
