### ISSUE TITLE
Docker,容器无法访问外网

### ISSUE THREAD

**Issue by pang1986267** [linkease/istoreos#104]
在容器内的控制台ping不通外网，但是可以ping通虚拟机和桥接网关172.17.0.1，内网ping都是正常的就是外网ping不懂，看了很多文章也搞试了很多方法都不行，后来在 云服务器上也装了 Docker 按照一样的步骤操作 云服务器上ping外网是正常的

**Comment by genesis-lua** [comment]
从外网ping docker可以吗？防火墙设置了吗

**Comment by jannson** [comment]
你可以设置端口转发啊，把端口映射出来，就可以外网访问了。或者可以做一个新的 docker 的桥，然后把整个桥加路由表。

软路由防火墙是肯定要开启的，免得太危险了。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3677/1
