### ISSUE TITLE
更新最新版本后 ssr 无法启动

### ISSUE THREAD

**Issue by oldboyooxx** [linkease/istoreos#105]
![image](https://user-images.githubusercontent.com/19473921/166695702-51d2edbc-be1a-4a83-a8f5-0910a3a4d649.png)

**Comment by genesis-lua** [comment]
重新安装试一下吧，可以使用的，正在用

**Comment by jannson** [comment]
对，升级最新的固件，保证有网络，然后重新安装。应该行，别人都测试了好多轮。请确认下。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3674/1
