### ISSUE TITLE
更新后阿里云 DDNS 为什么无法启用

### ISSUE THREAD

**Issue by oldboyooxx** [linkease/istoreos#106]
![image](https://user-images.githubusercontent.com/19473921/166697887-88322e80-3350-429d-823b-a932d265cd2d.png)
![image](https://user-images.githubusercontent.com/19473921/166697958-6de0fe97-451b-4667-bdfd-33dc150f8363.png)

为什么看日志里面输出的内容是初始值？是我的配置没有生效？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3672/1
