### ISSUE TITLE
EasePi最新固件，安装PassWall 等程序后，找不到对应软件启动入口

### ISSUE THREAD

**Issue by Roy2088** [linkease/istoreos#107]
EasePi最新固件，安装PassWall 等几个科学上网程序后。找不到程序；是不是有隐藏开关指令？

**Comment by jannson** [comment]
没有啥隐藏指令，在服务里面。
如果不行，就退出登录重新进来，或者 F12 打开浏览器，忽略缓存。肯定能出来。但是不会在软件中心出现
