### ISSUE TITLE
NTFS 格式不支持中文目录（导致 Samba 配置也无法支持中文）

### ISSUE THREAD

**Issue by lifaxian** [linkease/istoreos#11]
Samba不支持中文目录

**Comment by jannson** [comment]
收到，这个确实没亲自测试到。我们测试下。。。

**Comment by jannson** [comment]
经过测试，发现是可以支持的啊，你截图看看你得配置方法。

**Comment by shejishi2277** [comment]
注意斜杠,\

**Comment by jannson** [comment]
终于知道这个问题的核心了，是用了 NTFS 格式，不支持中文目录。。。

**Comment by jannson** [comment]
ntfs-3g 有中文字符支持的，不过要改一下fstab的NTFS分区文件格式 
/dev/<分区>  /mnt/<挂载目录> ntfs-3g silent,umask=0,locale=zh_CH.utf8 0 0

也就是 ntfs-3g 的挂载有 BUG，需要加上中文的支持

**Comment by jannson** [comment]
已经修复。

**Comment by lifaxian** [comment]
0506版还是不行，没有修复



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月7日(周六) 上午10:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [linkease/istoreos] NTFS 格式不支持中文目录（导致 Samba 配置也无法支持中文） (Issue #11)




 
已经修复。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3924/1
