### ISSUE TITLE
首页内存使用率显示不准确

### ISSUE THREAD

**Issue by longaga** [linkease/istoreos#113]
![E1ASI%HC2T}1YARU2 SJTOY](https://user-images.githubusercontent.com/25930270/167085331-55a47108-f5a6-44e1-ad9c-ffee024f27d1.png)
如题，首页内存使用率显示不准确，概览里的是准的

**Comment by jannson** [comment]
收到，我们看看为何这两者不一样。。。

**Comment by jannson** [comment]
最新版本修复了这个 UI 显示问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3656/1
