### ISSUE TITLE
考虑支持用户的软件中心的软件源的检查，保证能访问

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#114]
离线包安装失败，是因为用户的网络无法访问软件源，从而安装失败，倒是用户不知所措。考虑增加源的检查，不能访问则增加感叹号，让用户用向导去更新软件源。可以考虑跟网络检查放一起，如下图所示：

![image](https://user-images.githubusercontent.com/4100344/167094546-4fe20605-f49b-430a-8370-77be2ee864e3.png)

**Comment by houzi-** [comment]
我觉得哦可以在插件安装日志里加入安装报错提示，如果无法安装怎直接输出日志引导用户去修改软件源，这样直接明了

**Comment by genesis-lua** [comment]
> 离线包安装失败，是因为用户的网络无法访问软件源，从而安装失败，倒是用户不知所措。考虑增加源的检查，不能访问则增加感叹号，让用户用向导去更新软件源。可以考虑跟网络检查放一起，如下图所示：
> 
> ![image](https://user-images.githubusercontent.com/4100344/167094546-4fe20605-f49b-430a-8370-77be2ee864e3.png)

如果可以的话，还是希望能把GitHub上的一些软件合集和kmod组成istore的软件库，在软件包里按需自取就好

**Comment by jannson** [comment]
你说得这些，后续空闲了肯定会来做的。

**Comment by jannson** [comment]
软件源错误，已经支持，并且在首页还支持软件源修改。

![1652848995(1)](https://user-images.githubusercontent.com/4100344/168958806-3af6634c-2597-4b98-a6d1-95736acc57d8.png)

**Comment by gintokighost** [comment]
这个软件源怎么切换或是配置

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3653/1
