### ISSUE TITLE
希望能增加kcptun和frp插件

### ISSUE THREAD

**Issue by lnzoro** [linkease/istoreos#115]
希望能增加kcptun和frp插件

**Comment by jannson** [comment]
frp 貌似就有吧？

**Comment by jannson** [comment]
![image](https://user-images.githubusercontent.com/4100344/167235216-52a601a5-5e03-4ea7-b1aa-987fb4ab9432.png)

kcptun 需要结合其它插件才能一起使用，建议自己安装就好了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3650/1
