### ISSUE TITLE
网络存储-挂载网络共享-挂载 WebDAV 如何设定？试了几个方法都没有成功

### ISSUE THREAD

**Issue by Roy2088** [linkease/istoreos#117]
网络存储-挂载网络共享-挂载 WebDAV 如何设定？试了几个方法都没有成功。

挂载路径是本地路径还是远程路径？如何判断已经挂载成功？

**Comment by jannson** [comment]
试试今晚上的版本。很快发布了。

**Comment by jannson** [comment]
已经发布了。X86 也支持了。ARS2 早支持了。请确认下。

**Comment by Roy2088** [comment]
ars2，昨晚的最新版本。可以看到第一级的文件夹，进去没看到二级目录。有机会出个简易指南吧，感觉这个应该比挂Clouddriver简易，速度可能也好些
________________________________
发件人: Janson ***@***.***>
发送时间: 2022年5月7日 11:05
收件人: linkease/istoreos ***@***.***>
抄送: Roy ***@***.***>; Author ***@***.***>
主题: Re: [linkease/istoreos] 网络存储-挂载网络共享-挂载 WebDAV 如何设定？试了几个方法都没有成功 (Issue #117)


已经发布了。X86 也支持了。ARS2 早支持了。请确认下。

―

**Comment by Joker-lm** [comment]
网络存储那里有个挂载网络共享，请问怎么挂载webdav?试了好几次都不行，目前用的rclone挂载到本地的

**Comment by langoyb** [comment]
我也有这个疑问，怎么挂载webdav

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3645/1
