### ISSUE TITLE
希望大佬支持8125B 2.5G网卡！

### ISSUE THREAD

**Issue by yyyxxx1637** [linkease/istoreos#12]

**Comment by jannson** [comment]
貌似支持的啊，你的无法用？

**Comment by yyyxxx1637** [comment]
对的宝大，系统可以正常启动，但是始终无法获取的正确的IP，即使我设置了正确的地址段内固定IP，也无法正常上网。所以推测可能是驱动问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3921/1
