### ISSUE TITLE
无法显示目录文件

### ISSUE THREAD

**Issue by vipwuping** [linkease/istoreos#120]
FinalShell 等相关软件登陆无法显示目录文件
网上查了  缺少 SFTP 服务  这个要改进一下

**Comment by houzi-** [comment]
如果是缺少该服务的话，可以自己使用以下命令尝试安装看一下
````
opkg update && opkg install vsftpd openssh-sftp-server
````

**Comment by jannson** [comment]
我们有个 SFTP 插件，我看了下原来还没管理员同意上架。一会上架。

**Comment by jannson** [comment]
最新的版本默认加上了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3640/1
