### ISSUE TITLE
upup会突然就用不了，重启也不管用，设置都开了，可是我查了就是没开

### ISSUE THREAD

**Issue by fengjiuge1** [linkease/istoreos#121]
也重启了，还是不行，啥都还没碰就突然这样了

**Comment by fengjiuge1** [comment]
> 也重启了，还是不行，啥都还没碰就突然这样了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3639/1
