### ISSUE TITLE
LAN口添加端口问题

### ISSUE THREAD

**Issue by leafyelin** [linkease/istoreos#122]
使用softether需要在LAN里面添加一个虚拟端口，但是在LAN编辑里面的设备选项好像只能单选，无法再添加设备，请问怎么操作？

**Comment by leafyelin** [comment]
已经找到设置的地方了

**Comment by leafyelin** [comment]
> 使用softether需要在LAN里面添加一个虚拟端口，但是在LAN编辑里面的设备选项好像只能单选，无法再添加设备，请问怎么操作？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3637/1
