### ISSUE TITLE
首页是否可以加入网口使用情况，用了几个，用了哪个，是否会好点？

### ISSUE THREAD

**Issue by fengjiuge1** [linkease/istoreos#123]
还有是否能加入实时显示哪个IP网速显示

**Comment by houzi-** [comment]
这个类似于梅林的设备实时流量显示，在OP上原本没有，需要花时间去开发，我们会把你提到的功能加入到开发清单里面

**Comment by longaga** [comment]
> 这个类似于梅林的设备实时流量显示，在OP上原本没有，需要花时间去开发，我们会把你提到的功能加入到开发清单里面

猴子大神，麻烦把koolproxy也弄弄啊~离线安装的那个过滤效果很差，跟以前酷软里的没得比

**Comment by jannson** [comment]
有一个啊。首页菜单那里，有个内网 IP 速度显示的。

**Comment by jannson** [comment]
![1652072986(1)](https://user-images.githubusercontent.com/4100344/167344438-2ac7688d-4f71-418f-9075-ff4b5a07c8a3.png)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3635/1
