### ISSUE TITLE
ddnsto经常假死，看到是启动的，但是就是不能访问

### ISSUE THREAD

**Issue by lifaxian** [linkease/istoreos#13]
ddnsto经常假死，看到是启动的，但是就是不能访问。要关闭后重新启动才可以

**Comment by jannson** [comment]
等我放过 QQ 群，下次出问题的时候，到 QQ 群里，我用远程软件帮你远程看看

**Comment by lifaxian** [comment]
> 等我放过 QQ 群，下次出问题的时候，到 QQ 群里，我用远程软件帮你远程看看

qq群多少可以加入吗？

**Comment by jannson** [comment]
https://www.koolcenter.com/posts/117

**Comment by jannson** [comment]
出问题的时候找我们定位。 DDNSTO 的收费用户其实我们还有 VIP 微信群，可以考虑加 这个群，里面有开发者神马的，更方便处理。

**Comment by lifaxian** [comment]
加群了，但是还没通过！！麻烦给我看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linkease/istoreos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月19日(星期二) 上午9:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [linkease/istoreos] ddnsto经常假死，看到是启动的，但是就是不能访问 (Issue #13)





 
https://www.koolcenter.com/posts/117

**Comment by jannson** [comment]
收费用户后台就有微信二维码，直接扫码进入。就会自动进群了，不需要人通过的。你试试

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3920/1
