### ISSUE TITLE
老哥能不能下一版把UPNP加进去呢，我网上找到的都不成功。

### ISSUE THREAD

**Issue by yxllovecc** [linkease/istoreos#134]
老哥能不能下一版把UPNP加进去呢，我网上找到的都不成功。你是最靓的仔

**Comment by jannson** [comment]
新版本，已经支持了啊。请确认。

**Comment by yxllovecc** [comment]
哈哈 谢谢大佬

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3608/1
