### ISSUE TITLE
是否可以出一个硬盘空间管理功能？

### ISSUE THREAD

**Issue by oldboyooxx** [linkease/istoreos#137]
软路由的的硬盘很小
每次更新后插件会丢失
于是乎：导致我没办法卸载
现在磁盘空间已经满了，我找不到卸载之前安装的插件入口，怎么办？

**Comment by jannson** [comment]
最新版本的沙箱模式，可以解决你的这个问题。可以关注我们的文档或者B站账号：酷友社

到时候我们会有沙箱模式的教程。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3601/1
