### ISSUE TITLE
重启后所有设置丢失

### ISSUE THREAD

**Issue by kennyyoung-lab** [linkease/istoreos#138]
ESXi上安装的2022042317版本， 配置如下，磁盘挂载的是EXT4格式的/dev/sda1，
![image](https://user-images.githubusercontent.com/68530243/168311571-ab1171a0-5fbb-4eb2-b50c-d3758cac60f1.png)

安装配置好后一切工作正常，iStore可以更新到 v0.1.9-6，
![image](https://user-images.githubusercontent.com/68530243/168312131-427d8aa8-cd2a-4264-9d9d-e8c297d2e4d4.png)

但是重启后所有设置都会丢失，回到初始化的状态，iStore也会还原到旧版本。

在线升级能看到有新固件，可以下载，但是更新失败，
![image](https://user-images.githubusercontent.com/68530243/168311925-ff169928-2bd6-4355-8032-5f60b4e9dc71.png)

这是什么原因导致的呢？

**Comment by kennyyoung-lab** [comment]
找到原因了。。。虚拟机是光盘镜像启动， 无法写入， 每次重启就还原。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3599/1
