### ISSUE TITLE
請問iStoreOS X86可以安裝在Qhora-301W上嗎?

### ISSUE THREAD

**Issue by allen1392** [linkease/istoreos#14]
機型特色為高通IPQ8072A Hawkeye v2
兩個10G電口
想請教iStoreOS X86能否取代原廠韌體
或是有無支援計畫
感謝

**Comment by jannson** [comment]
这个并不是 X86 的系列。我们可能不会官方支持。但是可以自己用我们提供的开源组件编译出来。等我提供更多的信息参考！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3916/1
