### ISSUE TITLE
有没有istore内置的homebox内网测速的单独的AArch64的ipk插件包

### ISSUE THREAD

**Issue by x2287711259** [linkease/istoreos#142]
有没有istore内置的homebox内网测速的单独的AArch64的ipk插件包

**Comment by jannson** [comment]
我在你的另外一个 issue 回答了你的这个问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3588/1
