### ISSUE TITLE
网易云解锁安装错误

### ISSUE THREAD

**Issue by Seele-e** [linkease/istoreos#143]
![image](https://user-images.githubusercontent.com/68818361/168456011-13cc8292-9a5a-4d2e-93de-81a11aec492d.png)

**Comment by Pinehao** [comment]
先去下载两个依赖的ipk文件安装后再安装这个

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3585/1
