### ISSUE TITLE
AMD CPU 温度显示为0

### ISSUE THREAD

**Issue by terryzung** [linkease/istoreos#146]
AMD CPU 温度显示为0

**Comment by jannson** [comment]
明天的版本能修复。。。请等等。

**Comment by jannson** [comment]
看看修复了没有。刚发布新版本。

**Comment by terryzung** [comment]
还是CPU温度显示0，原来用爱快一直正常

**Comment by terryzung** [comment]
> 看看修复了没有。刚发布新版本。

还是CPU温度显示0，原来用爱快一直正常

**Comment by jannson** [comment]
请试试这个：sensors | grep -E 'temp1'

我们打算不自己实现了，用别人的命令行试试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3580/1
