### ISSUE TITLE
防火墙添加后不能删除

### ISSUE THREAD

**Issue by huojicache** [linkease/istoreos#147]
防火墙通-信规则中添加的规则删除后在状态-防火墙中依然能看到被删掉的规则

**Comment by huojicache** [comment]
> 防火墙通-信规则中添加的规则删除后在状态-防火墙中依然能看到被删掉的规则

-

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3577/1
