### ISSUE TITLE
请问应用商店 里面Ubuntu下载时没有完成就变成黄颜色页面了？

### ISSUE THREAD

**Issue by terryzung** [linkease/istoreos#149]
请问应用商店 里面Ubuntu下载时没有完成就变成黄颜色页面了？是docker问题还是没有适配？

**Comment by jannson** [comment]
这个需要后续版本来好好开发下。现在有界面超时问题。

**Comment by jannson** [comment]
此问题终于修复了！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3572/1
