### ISSUE TITLE
配置完旁路有 iStoreOS没有网 下面的lan口有网

### ISSUE THREAD

**Issue by wanglongfei8899** [linkease/istoreos#15]

**Comment by jannson** [comment]
可能旁路由里面的 CPU 没配置 DNS，你手动配置一个 DNS 里面就有网络了。请试试。。。

**Comment by wanglongfei8899** [comment]
![image](https://user-images.githubusercontent.com/75508757/163708415-23560c85-7866-4e0b-90bd-9e4bcfbd2c5

**Comment by wanglongfei8899** [comment]
![c1c9de3f1156714a077ca622ab6fd2a](https://user-images.githubusercontent.com/75508757/163708496-dd0e4c75-e3d0-475f-b7ca-90fa55931c6f.png)
![9dd4950806e2a5e6824beabf3ed86ef](https://user-images.githubusercontent.com/75508757/163708497-92bc5d68-4b28-42a6-8371-601f11b2d5d4.png)

**Comment by wanglongfei8899** [comment]
是不是我哪里设置有问题  但是可以正常上网 就是固件不能 更新软件包 也ping不通外网

**Comment by wanglongfei8899** [comment]
主路由是开HDCP的   iStoreOS是关闭DHCP的

**Comment by wanglongfei8899** [comment]
奇葩 给iStoreOS换个地址 iStoreOS有网了 然后下面LAN口没网了 还能这样

**Comment by jannson** [comment]
核心就是 DNS 错误导致没网络。你把DNS 改成：223.5.5.5 223.6.6.6 试试。
可以在路由器里面 ping 223.5.5.5 试试

**Comment by mmmqx827** [comment]
我的小主机软路由安装istoreOS后能够上网，但是安装网页提供的第三方科学项目的插件，配置好后显示未启用，重启也一样，现在passwall和ss都是这个情况，麻烦问一下怎么解决，谢谢

**Comment by jannson** [comment]
旁路由问题解决了，我关闭这个 issue了。第三方的插件问题，会有第三方的人修复的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3912/1
