### ISSUE TITLE
0518版本升级后，首页的互联网连接时间和IPV4及IPV6地址无法显示

### ISSUE THREAD

**Issue by milhu** [linkease/istoreos#151]
群里小伙伴也有相同问题，前面几版升级都未发现问题
![429FB414E76B22735D0777B44520A53F](https://user-images.githubusercontent.com/12318000/168968025-bc783d5a-a841-4575-8a2e-43c4696c0ef7.png)
。

**Comment by gkl1368** [comment]
做旁路的时候，这里如何显示ipv6地址？谢谢

**Comment by bailliesun** [comment]
我也遇到了同样的问题

**Comment by nemo830** [comment]
我的也是 ipv6不显示 还有16g内存爆满

**Comment by milhu** [comment]
宝哥他们已经查过我机子上的后台了，找到问题点了，应该会在下个版本修复的。

**Comment by fulracoco** [comment]
同遇到了。 重启了好次，才正常。 拨号成功了， 有设备不能上网，而有的设备能上网， dhcp分配页面也没有看到设备，
op自身却也不能联网。

**Comment by milhu** [comment]
> 同遇到了。 重启了好次，才正常。 拨号成功了， 有设备不能上网，而有的设备能上网， dhcp分配页面也没有看到设备， op自身却也不能联网。

我的只是单纯的不显示，但是不影响使用，跟你描述的情况还不尽相同

**Comment by jannson** [comment]
应该今天修复。

**Comment by gkl1368** [comment]
> 应该今天修复。

作为旁路 单lan口，还是不显示。

**Comment by molin830** [comment]
> 群里小伙伴也有相同问题，前面几版升级都未发现问题 ![429FB414E76B22735D0777B44520A53F](https://user-images.githubusercontent.com/12318000/168968025-bc783d5a-a841-4575-8a2e-43c4696c0ef7.png) 。



> 应该今天修复。

大神 518 519 开机一会16g内存就爆满
![FT1(YLX)UB5B3H)}0D N%LT](https://user-images.githubusercontent.com/46592253/169291107-45ab3f36-0ef3-465e-bbb3-6b78f50c861d.png)

**Comment by jannson** [comment]
内存爆满是因为内存跑到 buff/cache 里面了，目前原因未知。

**Comment by jannson** [comment]
已经修复。

**Comment by gkl1368** [comment]
> 已经修复。

最新的0525还是不显示v6地址

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3568/1
