### ISSUE TITLE
因为开启 IPv6，软件中心无法安装插件

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#156]
### 现象

* 部分用户无法离线安装软件
* 部分用户无法在线安装软件

### 原因：

* 部分用户有拿到 IPv6，但实际上 IPv6 无法上网。导致软件中心默认用 IPv6 而无法更新软件包。
* 因为开启了 mwan 导致 IPv6 无法访问外网

### 最简单解决办法：

* 用户关闭 IPv6
* 首页切换软件源到腾讯云（貌似这个没 IPv6）

### 固件深层解决

1. opkg 安装软件包，设置超时时间
2. opkg 安装软件包，优先用 IPv4

**Comment by jannson** [comment]
已经修复，opkg 增加了超时时间，并且增加了软件源的修改，选择腾讯云可以避免走 IPv6

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3555/1
