### ISSUE TITLE
能否告知首页显示温度的代码在哪个文件。

### ISSUE THREAD

**Issue by hx801217** [linkease/istoreos#158]
/usr/lib/lua/luci/view/admin_status/index.htm里面找过了，没找到。
因为我是AMD的cpu，需要加上<tr><td width="33%"><%:CPU Temperature%></td><td><%=luci.sys.exec("sensors  | grep -E 'temp1'")%></td></tr>代码，和安装lm-sensors才能显示，想请问下具体的位置，或者是怎么实现的

**Comment by jannson** [comment]
感谢，等我们解决。首页的页面比较复杂，用这样的方法行不通。

**Comment by jannson** [comment]
如果之前的计算方法行不通，并且有 sensors 的时候，则尝试用 sensors 来计算温度：

![image](https://user-images.githubusercontent.com/4100344/169776530-ac231fe3-10d5-41d4-a66e-617e8d366bde.png)

**Comment by jannson** [comment]
请升级最新版本试试。我们还是没用 sensors，但是自己写了代码，应该支持了，不支持再打开此 issue

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3551/1
