### ISSUE TITLE
519版本升级后应用商店再装其他插件在已安装里面什么都没有了！

### ISSUE THREAD

**Issue by terryzung** [linkease/istoreos#159]
519版本升级后应用商店保留上个版本的插件，但是再装其他插件在已安装里面什么都没有了，在全部软件里面安装任何插件，在已安装里面不会出现！

**Comment by jannson** [comment]
会不会类似这个问题：https://github.com/linkease/istoreos/issues/156

你用 ssh，进去：

ps -ef|grep opkg

看看是不是安装插件卡住了，导致出不来。
或者也可以重启试试。

**Comment by terryzung** [comment]
> 会不会类似这个问题：#156
> 
> 你用 ssh，进去：
> 
> ps -ef|grep opkg
> 
> 看看是不是安装插件卡住了，导致出不来。 或者也可以重启试试。

软件安装成功了，只是应用商店已安装不能用了。

**Comment by xie8fei** [comment]
遇见同样问题，刷回518也没有恢复

**Comment by jannson** [comment]
请刷最新版本。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3550/1
