### ISSUE TITLE
SNMP 状态正常，不能获取

### ISSUE THREAD

**Issue by hongbin75513** [linkease/istoreos#160]
基本网络配置：
爱快主路由，iStoreOS旁路由
iStoreOS安装了snmpd 5.8-2版本，爱快设置跨三层应用，状态显示正常，但不能正常使用，爱快看不到iStoreOS下的设备。

**Comment by hongbin75513** [comment]
找到问题了，open clash 兼容模式下，snmp功能失效。切换到TUN模式正常。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3548/1
