### ISSUE TITLE
519版本 无法虚拟机安装 

### ISSUE THREAD

**Issue by pharder56k** [linkease/istoreos#161]

**Comment by jannson** [comment]
收到，确实，EFI 也不知掉为何安装不到虚拟机上了。

**Comment by jannson** [comment]
请尝试这个内测版本：https://fw.koolcenter.com/iStoreOS/alpha/

**Comment by bg4dew** [comment]
这个可以启动，但缺少8156B网卡驱动

> 请尝试这个内测版本：https://fw.koolcenter.com/iStoreOS/alpha/

**Comment by haoboot** [comment]
519版本 虚拟机安装卡clocksurce:switched to clocksource tsc

**Comment by jannson** [comment]
请刷最新版本测试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3546/1
