### ISSUE TITLE
519版本 虚拟机安装卡clocksurce:switched to clocksource tsc

### ISSUE THREAD

**Issue by haoboot** [linkease/istoreos#162]

**Comment by jannson** [comment]
请尝试 alpha 版本：https://fw.koolcenter.com/iStoreOS/alpha/

**Comment by jannson** [comment]
最新版本应该好了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3544/1
