### ISSUE TITLE
J1900 SSH wan或者wan6执行命令网口重启

### ISSUE THREAD

**Issue by dnpl** [linkease/istoreos#164]
![IMG_20220521_044639](https://user-images.githubusercontent.com/22452022/169608533-f066eac9-9746-40c6-83ac-a1b51b46eb73.jpg)
通过wan或者wan6连接执行命令，会卡着，查看日志显示连接丢失，防火墙重启，用的是最新的固件。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3539/1
