### ISSUE TITLE
UEFI版本

### ISSUE THREAD

**Issue by agate520** [linkease/istoreos#165]
上一个版本可以 这次在线更新直接打不开 从新安装也不行。PVE安装 X86EFI固件

**Comment by jannson** [comment]
这个 alpha 版本可以了：https://fw.koolcenter.com/iStoreOS/alpha/

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3537/1
