### ISSUE TITLE
519版本 磁盘无法网络共享 占用内存无法释放

### ISSUE THREAD

**Issue by nemo830** [linkease/istoreos#166]
519版本 磁盘无法网络共享 占用内存无法释放
![Uploading F752D570-D8F9-4EC6-B22C-13D6AF31E639.png…]()

**Comment by nemo830** [comment]
内存一直处在98~99%

**Comment by nemo830** [comment]
电脑打开挂载的磁盘一直显示用户名或者密码错误

**Comment by wildtigerw** [comment]
对，我的内存占用也是长时间99%

**Comment by jannson** [comment]
跟问题：https://github.com/linkease/istoreos/issues/169 相同。先关闭这个。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3535/1
