### ISSUE TITLE
使用网心云时网络时端口限制，如何改善？

### ISSUE THREAD

**Issue by hikaru2025** [linkease/istoreos#168]
istoreOS是主路由器，网心云是通过另一台nas的虚拟机运行，大家都在同一网段，nas和路由器通过交换机连接，请问istoreOS能否通过设置upnp或其他nat规则来改善网络类型？

**Comment by hikaru2025** [comment]
nothing

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3530/1
