### ISSUE TITLE
手动安装的插件，如何删除

### ISSUE THREAD

**Issue by huaxiac4** [linkease/istoreos#170]
RT，手动安装的插件不会在【已安装】中显示，请问要如何卸载？

**Comment by jannson** [comment]
目前没有办法，只能在软件包那里，一个一个手动卸载。确实很麻烦。

下一步我们有个沙箱模式，可以比较好的解决这样的问题。

最彻底的解决，还是离线包提供卸载的功能。目前确实把这个问题归类为无法解决。以后再说吧。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3525/1
