### ISSUE TITLE
docker 拉取bug

### ISSUE THREAD

**Issue by Alex-NKG** [linkease/istoreos#171]
docker pull的时候过一段时间返回：
Bad Gateway
The process did not produce any response
已经尝试不同镜像

**Comment by jannson** [comment]
是用网页，还是用命令行里面？

用网页，确实拉取大的镜像是不行的。

**Comment by longaga** [comment]
星期天我拉nextcloud也遇和楼主一样的问题，但今天拉成功了

**Comment by jannson** [comment]
请升级最新版本测试，尝试把 Docker 的路径切换到另外一个硬盘试试，也可以修改下 Docker 的镜像试试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3522/1
