### ISSUE TITLE
【严重问题】kernel: overlayfs: invalid origin (root/bmcweb_persistent_data.json, ftype=8000, origin ftype=4000)

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#173]
严重性问题。就是升级之后，导致 overlayfs 不同步，然后系统的很多文件无法读取。从而导致系统无法用。
相关信息：

https://git.codinge.cn/nas-kernel/linux/commit/a888db310195400f050b89c47673f0f8babfbb41.patch

https://lore.kernel.org/kernelnewbies/29d44208.9fc.178d85082a4.Coremail.ouyangxuan10@163.com/T/

临时解决办法：v0506 升级上来的，都不能保留配置升级。

**Comment by jannson** [comment]
### 测试用例1：

1. 不保留配置升级到v0518：https://fw.koolcenter.com/iStoreOS/x86_64/openwrt-21.02.2-2022051808-x86-64-squashfs-combined.img.gz
2. v0518 安装很多插件，包括离线插件
3. 配置插件
4. 保留配置升级到 alpha 版本：https://fw.koolcenter.com/iStoreOS/alpha/openwrt-x86-64-generic-squashfs-combined.img.gz

查看系统日志跟内核日志，看是否有 overlayfs 文件错误

### 测试用例2

1. 不保留配置升级到v0506：https://fw.koolcenter.com/iStoreOS/x86_64/openwrt-21.02.1-2022050620-x86-64-squashfs-combined.img.gz
2. v0506 安装很多插件，包括离线插件
3. 配置插件
4. 保留配置升级到 alpha 版本：https://fw.koolcenter.com/iStoreOS/alpha/openwrt-x86-64-generic-squashfs-combined.img.gz

**Comment by jannson** [comment]
应该是运行时检查，系统被升级之后，导致认为系统变化而不同步！

![0b95053a89fdc411ea213649764f8bb](https://user-images.githubusercontent.com/4100344/169747133-abbc2a28-5f56-4d58-b808-7b6ee9713475.jpg)

![38b2041edfda9ef60cdcb6646057c9a](https://user-images.githubusercontent.com/4100344/169747151-350d7d5b-2065-44b6-8e7e-1c5bb3b1733f.jpg)

**Comment by jannson** [comment]
如果出现问题，请尝试：https://fw.koolcenter.com/iStoreOS/alpha/

更新 alpha 固件进行测试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3517/1
