### ISSUE TITLE
WAN口获取到IP不能上网

### ISSUE THREAD

**Issue by elbert1996** [linkease/istoreos#178]
WAN口成功拨号获取到IP后不能上网 istoreos应用商店也连不上 重刷固件后恢复正常

**Comment by jannson** [comment]
首页显示啥错误？

**Comment by jannson** [comment]
这个问题无法重现，今天刚更新的最新版本比较稳定，可以用这个版本测试！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3506/1
