### ISSUE TITLE
索尼电视无法自动获取IP

### ISSUE THREAD

**Issue by touzi** [linkease/istoreos#180]
1. 系统重启后索尼电视无法自动获取IP, 需要关闭电视Wi-Fi后重新打开就可以获取了. lan网络设置是默认的, wan是拨号上网. 

2. cpu占用 100% , 这个可能和我安装了一部分插件, 或者是我扩容 /overlay 但没有到达我想要的效果, 后来查了是 istoreOS 系统好像屏蔽了这个功能, 然后我有卸载了扩容还原到系统默认情况了. 

固件版本
OpenWrt 21.02.2 2022052508
内核版本
5.4.179

**Comment by touzi** [comment]
cpu占用100% 是因为出现了回环, 我自己解决了.

**Comment by jannson** [comment]
iStoreOS 扩容用首页的沙箱模式。我们的 overlay 是为沙箱模式准备的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3501/1
