### ISSUE TITLE
OpenWrt 21.02.2 2022051913 安装SSR PLUS 插件之后只有ss V2R等选项就没有SSR选项

### ISSUE THREAD

**Issue by bigmofy** [linkease/istoreos#184]
![1653584334(1)](https://user-images.githubusercontent.com/106338969/170537743-7b56cf87-50d5-4e0c-8afc-b65a8d440b99.png)
试了好几次了

**Comment by bigmofy** [comment]
是插件下载不完整问题，已经解决。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3492/1
