### ISSUE TITLE
lan口无法自动获取正确的ip地址

### ISSUE THREAD

**Issue by cc158602358** [linkease/istoreos#186]
安装好了iStoreOS，软路由pppoe拨号上网成功，内网设置网段为192.168.100.1，小米路由器设置成有线中继模式，但是手机电脑连接不管是WiFi还是软路由都获取ip网段都为192.168.1.x，手动改成正确网段可以上网，研究了2天了还是不知道问题出在哪里？请问大神怎么解决？感谢

**Comment by jannson** [comment]
很可能内网还有其他的 DHCP 服务器，导致 iStoreOS 会自动关闭自己的 DHCP 通告。可以看 系统日志看到相关信息。

建议你好好找找，看看内网是不是把光猫的 DHCP 也接到了内网来了？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3488/1
