### ISSUE TITLE
Ubuntu 插件安装错误

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#19]
因为里面判断了 docker not in disk 但是没判断好。代码已经更新，但是插件没上传。同时现在的界面比较丑陋

**Comment by gintokighost** [comment]
x86还是不能安装

**Comment by gintokighost** [comment]
![12313313](https://user-images.githubusercontent.com/103917782/176116316-3d8902ad-1187-46b2-b3d0-f5fd2bfc7f6f.jpg)

**Comment by gintokighost** [comment]
这个问题解决了，是硬盘空间不足造成的。另外在开启DDNS.to里用Ubuntu 桌面链接不能打开，只能在本地用吗Ubuntu 桌面

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3903/1
