### ISSUE TITLE
519固件在线升级526下载报错

### ISSUE THREAD

**Issue by huaxiac4** [linkease/istoreos#195]
在线升级
下载失败
`curl:(3)Error`
<img width="360" alt="微信截图_20220601210308" src="https://user-images.githubusercontent.com/3352142/171411860-dd5f3571-fcdc-430d-ab3f-568460e76032.png">

**Comment by jannson** [comment]
对的，这个问题我发公告了。只能手动升级到下个版本。后面的版本没这个问题了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3467/1
