### ISSUE TITLE
D2550  CPU温度0

### ISSUE THREAD

**Issue by Robin-JW** [linkease/istoreos#196]
CPU温度显示0，0526版本正常

型号 | GuoGuang IC2M1028V-J
架构 | Intel(R) Atom(TM) CPU D2550 @ 1.86GHz
Target Platform | x86/64
固件版本 | OpenWrt 21.02.2 2022060116 / LuCI openwrt-21.02-cn branch git-22.135.19704-132fbcf

**Comment by Jason-ka** [comment]
我也有同样的问题，希望尽快修复一下～

**Comment by jannson** [comment]
来群里，给我远程看看。很多平台，每个平台获取的温度方式不一样。只能遇到一个，解决一个。

**Comment by Robin-JW** [comment]
> 来群里，给我远程看看。很多平台，每个平台获取的温度方式不一样。只能遇到一个，解决一个。

TG群么？没找到您，或者您在TG群联系我？ 「Robin灬桑」

**Comment by Robin-JW** [comment]
OpenWrt 21.02.2 2022061019 / LuCI openwrt-21.02-cn branch git-22.160.13453-cb18896 
已修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3464/1
