### ISSUE TITLE
Jellyfin 插件安装错误

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#20]
因为之前的 Jellyfin 是基于 ARS2 的，还没切换到 X86 过来。需要修复插件问题

**Comment by btcwf** [comment]
大神，Jellyfin安装失败，D525的主板，是不是因为板子太老不支持啊

**Comment by zzk1996** [comment]
一样的情况，拉取镜像解压到一半多的时候就报黄，拉取docker hub 的就没这个问题

**Comment by jannson** [comment]
Jellyfin 终于有空修复了。明天会重新上架软件中心。。。不会有报黄等等问题了

**Comment by tolshao** [comment]
@jannson jellyfin插件好像还是不对，昨天插件能装上，然后docker运行不起来；
今天的话是插件装好（没报错），但是luci界面为空白（不显示）；
系统重新刷过，还是不行，机子是j4125

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3900/1
