### ISSUE TITLE
希望出不带Docker 版本，Docker 对游戏加速有影响

### ISSUE THREAD

**Issue by gaohanping** [linkease/istoreos#203]
希望出不带Docker 版本，Docker 对游戏加速有影响

**Comment by cnfjice** [comment]
不适用即可，怎么会有影响，把docker的网卡删除就好了。

**Comment by gaohanping** [comment]
> 不使用即可，怎么会有影响，把docker的网卡删除就好了。

**Comment by gaohanping** [comment]
> 不使用即可，怎么会有影响，把docker的网卡删除就好了。

可以这样就解决吗？网卡删除就OK了？

**Comment by jannson** [comment]
有一个启动项，启动项里面，可以关闭 Docker，停止掉。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3450/1
