### ISSUE TITLE
r4s无法重启

### ISSUE THREAD

**Issue by byteinfo** [linkease/istoreos#205]
系统和reboot命令重启都无法启动，重启后一直亮红灯。
版本0607。

**Comment by jannson** [comment]
貌似确实有这个问题。等等看。。。

**Comment by byteinfo** [comment]
刚更新了2022061017版本还是不能重启😡

**Comment by byteinfo** [comment]
之前Balenaetcher写固件无法重启，这次用rufus写固件竟然可以重启了。。。

**Comment by MichioY** [comment]
OpenWrt 21.02.2 2022071511
同样问题 页面重启没反应 要拔电才行

**Comment by supen8012** [comment]
用的最新的openwrt-2022071511-nanopi-r4s-squashfs.img.gz，无论用Balenaetcher还是rufus写固件，系统菜单的重启都失败，一直亮红灯，刷了几遍了，特来请教，怎么才能让重启功能正常？期待用上ISTOREOS的固件！

**Comment by supen8012** [comment]
用的最新的openwrt-2022071511-nanopi-r4s-squashfs.img.gz，无论用Balenaetcher还是rufus写固件，系统菜单的重启都失败，一直亮红灯，刷了几遍了，特来请教，怎么才能让重启功能正常？期待用上ISTOREOS的固件！

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3085/1

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3447/1
