### ISSUE TITLE
剥离docker

### ISSUE THREAD

**Issue by Omoinemie** [linkease/istoreos#212]
目前固件默认是集成了docker的，很多人并不需要，可以剥离出来让用户自主安装。

**Comment by longaga** [comment]
你不用不代表别人不用啊，你不用开机启动项禁用就是

**Comment by jannson** [comment]
我们之前想过，但是考虑到，我们将来要支持的是以软路由为主，并且还将给 Docker 开发很多的功能（开发中）
目前默认带上了 Docker。我们考虑放首页，加一个快捷的关闭 Docker 的功能。

未来我们的软件中心很多插件会依赖 Docker，比如：

1. 影院
2. 下载
3. 带 AI 的智能相册
4. 更强大的 DDNS 设置
5. 更漂亮的个人导航页

等等。Docker 对普通用户来说，他们不懂如何安装。默认带上可能他们会注意到

**Comment by tchenjian** [comment]
强烈建议 Docker 支持卸载
![image](https://user-images.githubusercontent.com/18399445/178429302-31a30722-bd70-4e8a-a39d-731ed8ab8f7d.png)
虽然是软路由, 但不希望他有太多额外的功能, 给的配置相对较低, 内存较小, 有了Docker , 内存时刻保持 100%
对希望轻量软路由来说, 这是个灾难

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3437/1
