### ISSUE TITLE
流量统计添加对接口选择的支持

### ISSUE THREAD

**Issue by Omoinemie** [linkease/istoreos#213]
目前的统计不知道是基于什么的，高玩一般会添加很多接口，不同名称。希望首页的流量统计能支持系统所有的接口，用户可自主选择接口查看流量详情。
像宝塔面板的那个一样。
![image](https://user-images.githubusercontent.com/31991443/173228044-df52b6cc-23f2-4864-ba23-d848f920732b.png)

**Comment by jannson** [comment]
目前这里有个，但是我们还没放到首页：

![image](https://user-images.githubusercontent.com/4100344/173729769-d494a6c3-83b3-4603-8183-7eba2f4b18f4.png)

**Comment by jannson** [comment]
可以在首页加一个更详细流量统计的菜单。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3436/1
