### ISSUE TITLE
br-lan: received packet on eth2 with own address as source address (addr:00:e2:69:**:**:**, vlan:1)

### ISSUE THREAD

**Issue by tommytianhm** [linkease/istoreos#216]
日志里面好多错误，不知是否有影响。
![image](https://user-images.githubusercontent.com/77065514/173341397-1019f8ff-7bed-4b2a-87e9-390c66985a7a.png)

**Comment by jannson** [comment]
嗯，是的。目前确实，我们还不知道怎么回事。
但是并不影响，我估计是有 miniupnpd 不支持的网络接口，导致发送数据失败，一直报错。。。

这个问题暂时标记为不解决。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3434/1
