### ISSUE TITLE
修复下istore里的jellyfin

### ISSUE THREAD

**Issue by gogogogood** [linkease/istoreos#221]
只有ARM64版本，没有x86的版本

**Comment by jannson** [comment]
这个问题呢，我们在大改，做了一个通用组件来支持。目前接近尾声了。。。

**Comment by jannson** [comment]
终于修复了。。。明天更新软件中心。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3429/1
