### ISSUE TITLE
OpenWrt 21.02.2 2022061019 版本安装离线工具包无法刷新出来

### ISSUE THREAD

**Issue by damen1983** [linkease/istoreos#224]
升级之后重新尝试安装离线工具包（passwall，openclash等），但是无论如何刷新，都无法刷新出已安装工具包

**Comment by Ricky-zou** [comment]
> 升级之后重新尝试安装离线工具包（passwall，openclash等），但是无论如何刷新，都无法刷新出已安装工具包

是arm架构的软路由吧？要安装支持环境才能装passwall，默认都是精简的，翻墙的软件都装不上去的。

**Comment by jannson** [comment]
离线包目前不在已安装里面，在服务里。
这个项目不负责相关问题，到相关项目去咨询。
