### ISSUE TITLE
x86 刚刷完机后 检测升级 报错

### ISSUE THREAD

**Issue by zb737472783** [linkease/istoreos#23]
![image](https://user-images.githubusercontent.com/2137950/163758828-71e7044c-3e2a-41ae-a6db-f25659b6eda6.png)

这个怎么解决啊...

**Comment by zb737472783** [comment]
parted -l  用这个命令修复后 现在报错 
![image](https://user-images.githubusercontent.com/2137950/163767420-9b537a75-b8de-490a-a901-38725d97a61a.png)

**Comment by jannson** [comment]
下个版本修复，可以考虑先手动升级。当根目录有其它分区的时候，我们的升级判断有问题。

**Comment by zb737472783** [comment]
收到!

**Comment by gonboy** [comment]
原来2G调整为10G 后， 升级导致第2(10G)，3个(50G)分区内容 全没了。 现在后续不敢改2G的大小了。
还是用默认的2G吧

**Comment by jannson** [comment]
分区不能随便改，2G  安装软件足够用了。如果实在不够用，以后也会有沙箱模式（多个 overrlay 分区）的扩容办法。总之最好别自己去调整

**Comment by zzyhdn0928** [comment]
(https://fw.koolcenter.com/iStoreOS/x86_64/openwrt-21.02.1-2022041521-x86_64-squashfs-combined.img.gz)这个版本升级仍然报错 离线安装软件也报错

**Comment by zzyhdn0928** [comment]
![befcfcd56ad23598d519e02c15c27d1](https://user-images.githubusercontent.com/103996132/163974166-e20e3289-3c96-4140-9f47-3b494d359a7d.png)

**Comment by zb737472783** [comment]
> ![befcfcd56ad23598d519e02c15c27d1](https://user-images.githubusercontent.com/103996132/163974166-e20e3289-3c96-4140-9f47-3b494d359a7d.png)

一样,等下个版本

**Comment by zzyhdn0928** [comment]
![df801ea1d58ce9cff3b46402be76e13](https://user-images.githubusercontent.com/103996132/163974618-72fd2b51-86a1-448a-abf9-ffd50423bc38.png)

**Comment by zzyhdn0928** [comment]
![45037d34d4734d495418f8324b25a70](https://user-images.githubusercontent.com/103996132/163974696-854765da-0492-4852-8573-ff5e5b178db3.png)

**Comment by jannson** [comment]
我知道了，很可能你路由器里面没网络。。。所以检测都失败了。你路由器里面，有个网络工具，ping www.baidu.com 试试。

**Comment by zzyhdn0928** [comment]
![d7a3ce8759875e6a33aaf99ae87af79](https://user-images.githubusercontent.com/103996132/164345229-78a5a526-9d22-41bf-83ab-d05fa0863c56.png)
![897afc5866446cc9d71859cda137367](https://user-images.githubusercontent.com/103996132/164345248-e9f54eab-17a0-4cad-8437-81b09382f2b6.png)
ping 百度也不通

**Comment by zzyhdn0928** [comment]
旁路由模式

**Comment by jannson** [comment]
你的DNS 是自动获取的，你手动改 DNS：223.5.5.5
试试。应该就有网络了，然后就可以安装并且在线升级了

**Comment by zzyhdn0928** [comment]
好的 我试试

**Comment by jannson** [comment]
先手动升级，下个版本就可以了。修复了这个问题。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3890/1
