### ISSUE TITLE
【严重问题】有多个硬盘，导致无法启动系统

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#233]
好不容易才知道这个问题，有多个硬盘的时候，X86 软路由竟然无法启动！

**Comment by huaxiac4** [comment]
我也遇到了，但是好像在bios改了某项设置以后就好了。不改也行。。多插拔几次电源，多启动几次就行了

**Comment by jannson** [comment]
用最新的版本 OK 了。貌似因为 grub 的一个错误导致。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3414/1
