### ISSUE TITLE
提供更简单的 iStoreOS 插件开发能力

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#235]
目标：让不懂 OpenWRT 的插件开发流程，编译流程的其它用户，能用个一键脚本，就能开发 iStoreOS 的插件，从而更好的补充软件中心的插件应用。

**Comment by jannson** [comment]
![image](https://user-images.githubusercontent.com/4100344/175436765-28c180ab-0015-49cd-8ed2-938eb003b88a.png)

**Comment by jannson** [comment]
目前只是实验版本。

**Comment by jannson** [comment]
已经完成，通过 json form 可以快速开发插件：https://github.com/linkease/nas-packages-luci/tree/main/luci/luci-lib-iform

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3411/1
