### ISSUE TITLE
luci Argon 皮肤导致 403 问题

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#24]
每天更新 bing 地址导致出错。

**Comment by jannson** [comment]
搞了半天，这个问题还没修复，非常尴尬。

**Comment by jannson** [comment]
这回应该修复了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3887/1
