### ISSUE TITLE
固件带的 qBittorrent下载的 web ui 的密码是多少?  

### ISSUE THREAD

**Issue by ql4321** [linkease/istoreos#242]
我这里找不到默认的web ui的密码

**Comment by yequanqing** [comment]
adminadmin

**Comment by sujianrong88** [comment]
亲 我知道问题 你把端口8080  改一下就行了 我也遇到 现在可以用了 我改8081

**Comment by sujianrong88** [comment]
密码还是一样的配方 账号 admin  密码 adminadmin

**Comment by jannson** [comment]
我录制视频的时候也发现了。可以换个配置文件的路径，然后就神奇的 OK 了！

**Comment by ql4321** [comment]
thanks

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3402/1
