### ISSUE TITLE
手动安装插件后不能键入UI

### ISSUE THREAD

**Issue by zhdw22114632** [linkease/istoreos#247]
esxi虚拟机下安装，可以设置网络成功联网，手动安装插件后重启，不能进入UI，不能联网

**Comment by jannson** [comment]
可以尝试今天的最新版本！之前的虚拟机安装，根目录大小有问题。好不容易才知道

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3395/1
