### ISSUE TITLE
证书问题

### ISSUE THREAD

**Issue by huojicache** [linkease/istoreos#249]
![有问题证书](https://user-images.githubusercontent.com/37629177/174760002-28313f1d-5f7b-4aad-9fe9-1fa47dc50de2.png)
![无问题证书](https://user-images.githubusercontent.com/37629177/174760091-23b454e5-55c2-40f1-80dd-ac4a2e4348ef.png)

在openwrt ssh中用curl访问这个机构签署证书的网站会报错，
证书机构自己的网站访问没问题，机构给其他网站签署的证书就有问题
![image](https://user-images.githubusercontent.com/37629177/174760793-596f4ea6-8621-42bc-9dc0-a7947ef5df72.png)
![image](https://user-images.githubusercontent.com/37629177/174760896-b0a8a892-5c0e-4178-a235-5db22734d7ba.png)

**Comment by jannson** [comment]
应该是固件本地根证书没包含你的目标网站的证书，估计得把目标网站的证书下载，并放入根证书才行。。。
根证书是跟随 OpenWRT 官方稳定分支的，我们应该不会随意去修改。
