### ISSUE TITLE
x68 固件的默认root密码多少

### ISSUE THREAD

**Issue by heymoseamar** [linkease/istoreos#25]
最新的x68 固件的默认root密码多少
![QQ截图20220418155853](https://user-images.githubusercontent.com/11907715/163776836-24e3632c-62d8-495f-bc3a-fcce556f6d80.png)
？

**Comment by weiqt** [comment]
password

**Comment by heymoseamar** [comment]
我想问 root 的密码   root的密码 不是password         不是 admin的这个密码

**Comment by weiqt** [comment]
https://www.koolcenter.com/posts/144  root的密码就是password

**Comment by jannson** [comment]
肯定是：password
不是的化可能是哪里搞错了。

**Comment by ChinaParrot** [comment]
修改密码，就登陆不了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3884/1
