### ISSUE TITLE
笔记本安装IStore

### ISSUE THREAD

**Issue by donedonefly** [linkease/istoreos#250]
笔记本能够安装 iStore 吗？

**Comment by jannson** [comment]
可以的，没问题。就是选用 X86 版本就行了

**Comment by Antake2333** [comment]
> 可以的，没问题。就是选用 X86 版本就行了

笔记本安装了之后风扇不转,能解决吗

**Comment by Vinke2** [comment]
装了之后如何关闭屏幕

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3393/1
