### ISSUE TITLE
R68S  显卡驱动问题

### ISSUE THREAD

**Issue by litao1791** [linkease/istoreos#252]
目前系统用起来还是很不错的，尤其是docker和市场，但是jellyfin不能用，我尝试很多次，都不行，我猜测是应该没有显卡确定，用tty一试，果然是没有显卡，希望小宝大神能更新一下，这样我们就能用jellyfin看电影了，多谢

**Comment by jannson** [comment]
Jellyfin 目前暂时只支持 ARS2 的硬解码驱动，马上会支持 X86，而其他芯片没精力维护。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3391/1
