### ISSUE TITLE
请问可以教一下esxi的istoreos使用教程吗

### ISSUE THREAD

**Issue by xiaozhou1210** [linkease/istoreos#253]
请问可以教一下esxi的istoreos使用教程吗

**Comment by jannson** [comment]
暂时没得，我们来加一个。

**Comment by jannson** [comment]
前段时间你搞不定可能是命中了我们固件的一个 BUG。你用今天的版本试试。。。

过几天我们也出出教程。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3389/1
