### ISSUE TITLE
iStoreOs 适合用于X86 32位的机器的吗？

### ISSUE THREAD

**Issue by exbom** [linkease/istoreos#259]
INTEL ATOM N270适合用哪个版本的固件

**Comment by jannson** [comment]
无法支持 32 位，因为 32 位我们需要重新编译整个软件中心的各种插件，精力耗费很大，并且 32 位用的人很少。所以我们暂时不考虑。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3381/1
