### ISSUE TITLE
如何进行第三方开发

### ISSUE THREAD

**Issue by flybiubiu** [linkease/istoreos#26]
感谢作者贡献
请问怎么开发第三方插件，我看都是run格式，和koolshare下tar.gz有什么区别

**Comment by jannson** [comment]
.run 格式是标准的，它本质是一个脚本。跟 koolshare 自定义的 tar.gz 安装包不一样。我们也是基于第三方开源使用的 .run，我一会把项目地址，与生成方法放到这里来。

忘记加上这个相关的说明文档了

**Comment by flybiubiu** [comment]
好嘞，感谢+10086！

**Comment by jannson** [comment]
README 里面我增加了点内容，后续我们更新更详细的 wiki。这里不是 BUG，我先关闭了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3881/1
