### ISSUE TITLE
x86efi固件，jellyfin插件显示空白

### ISSUE THREAD

**Issue by tolshao** [linkease/istoreos#262]
<img width="572" alt="image" src="https://user-images.githubusercontent.com/22099608/176173694-1e320aef-be77-4f3a-95f2-4107f7a43829.png">
插件安装成功，但是“服务-jellyfin”下空白，不显示；
昨天能显示，但是安装到docker那启动不起来，所以今天重装报错如上。

**Comment by tolshao** [comment]
看到今天更新的插件已经修复了，感谢大佬

**Comment by tolshao** [comment]
但是open小猫咪插件，离线安装的，报错failed to signature

**Comment by jannson** [comment]
嗯。有个代码错误，嘿嘿。。。

可以自行搜索 .run 的离线包，这里不提供相关资讯。

**Comment by tolshao** [comment]
报错failed to signature那个解决了，软件源切换成清华的可以了；
然后网心云插件装上之后，docker也起来了，但是没显示绑定的那个界面了

**Comment by tolshao** [comment]
怎么检查jellyfin有没有硬解呢，我记得在哪看，插件装的是配好的，但是感觉放视频的时候cpu还是跑很满，
我进入docker容器发现“/dev”下并没有"/dri"目录，求大佬支招？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3377/1
