### ISSUE TITLE
求助能否提供一下udpxy插件的下载啊

### ISSUE THREAD

**Issue by xtwj8888** [linkease/istoreos#263]
能否提供一下udpxy插件的下载啊

**Comment by jannson** [comment]
是这个么？https://github.com/openwrt/luci/tree/master/applications/luci-app-udpxy

貌似可以的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3376/1
