### ISSUE TITLE
X86 安装完成修改默认密码password登陆不了

### ISSUE THREAD

**Issue by ChinaParrot** [linkease/istoreos#269]
修改默认password，登陆不了。是否用命令 passwd root 修改的？

**Comment by jannson** [comment]
不能用这个修改，要在界面上修改用户名密码。肯定是可以的

**Comment by ChinaParrot** [comment]
@jannson 能截图么？没有找到修改地方

**Comment by ChinaParrot** [comment]
> 不能用这个修改，要在界面上修改用户名密码。肯定是可以的

能截图么？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3368/1
