### ISSUE TITLE
希望增加适配J4125四网口RTL8125B瑞昱2.5G网卡的驱动

### ISSUE THREAD

**Issue by TZFcdd** [linkease/istoreos#27]
希望增加适配J4125四网口RTL8125B瑞昱2.5G网卡的驱动

**Comment by jannson** [comment]
好的。在考虑了

**Comment by jannson** [comment]
新版本已经支持，请测试。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3878/1
