### ISSUE TITLE
DDNS功能时间异常

### ISSUE THREAD

**Issue by HoyoEcho** [linkease/istoreos#270]
![image](https://user-images.githubusercontent.com/107328388/176655639-674b480b-dbc9-4c72-a8a1-d889ff387c53.png)
如图，DDNS插件自己的时间，与实际时间相比，要快好几分钟

**Comment by jannson** [comment]
可能你得路由器系统时间，比正常的快。尝试修改下 NTP 服务器试试。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3367/1
