### ISSUE TITLE
【closed】可以获取IPv6地址但不能访问IPv6网站

### ISSUE THREAD

**Issue by sumiles** [linkease/istoreos#276]
物理机安装，能获取到IPv6地址，但是访问不了IPv6网站
版本：OpenWrt 21.02.2 2022062120 / LuCI openwrt-21.02-cn branch git-22.165.12986-fdfc730
已经解决，passwll插件dns设置错误导致，可以关贴了

**Comment by sumiles** [comment]
已经解决，passwll插件dns设置错误导致

**Comment by mcmichaelchan** [comment]
> 



> 已经解决，passwll插件dns设置错误导致

@sumiles 请问你是如何修改passwall的设置从而解决问题的？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3360/1
