### ISSUE TITLE
用不了，路由器连接外网成功，但局域网设备连不上。

### ISSUE THREAD

**Issue by nh14174** [linkease/istoreos#279]
ping外网，上级路由，局域网内我的电脑都能通；但我的电脑就只能ping通iStore路由器，上级路由和外网都ping不通
![125280C13659E4286D919E5FD91ED6CF](https://user-images.githubusercontent.com/43104532/177037747-5cd7af80-d8d8-42f6-9ba2-d69a3db67f7e.png)
。

**Comment by jannson** [comment]
问题解决了吗？虚拟机安装的么？

这种 case 很可能你的路由器有两个 LAN，你可以确认下你的接口那里是不是设置正确。我估计你配置是有问题的。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3356/1
