### ISSUE TITLE
esxi虚拟机安装无限重启

### ISSUE THREAD

**Issue by xseruer** [linkease/istoreos#284]
安装版本：openwrt-21.02.2-2022062120-x86-64-generic-squashfs-combined-efi.img.gz
虚拟机：ESXI 7.0.2

启动页面如下：
![image](https://user-images.githubusercontent.com/4255288/177184130-201f524e-d25d-48d9-91db-02d9fd0fe1b4.png)

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3347/1
