### ISSUE TITLE
有没有脚本 能在终端中实时显示温度 负载 网速 之类监控

### ISSUE THREAD

**Issue by zb737472783** [linkease/istoreos#286]
物理机软路由一直接的显示器,想通过自带的终端 实时显示温度 负载 网速 之类监控

**Comment by jannson** [comment]
不好意思，目前我们不考虑支持这个。普通用户一般来说用不到，优先级很低。

我估计有很多开源项目可以支持。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3345/1
