### ISSUE TITLE
iStore在mac的safari浏览器中无法显示

### ISSUE THREAD

**Issue by zwtocn** [linkease/istoreos#287]
商店在chrome中能正常显示，但中safari中无法显示。safari版本 14.1.2 (14611.3.10.1.7)

**Comment by jannson** [comment]
请截图，以及最好 F12 截图，看看 console 里面的内容

**Comment by zwtocn** [comment]
> 请截图，以及最好的 F12 截图，看看控制台里面的内容
<img width="1229" alt="11" src="https://user-images.githubusercontent.com/14216519/177945528-bc187e26-9e5f-46f7-93b2-38452ba7910e.png">

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3344/1
