### ISSUE TITLE
为什么离线安装了passwall/ssr/helloworld，在已安装里都不显示？

### ISSUE THREAD

**Issue by chenxiccc** [linkease/istoreos#29]
为什么离线安装了passwall/ssr/helloworld，在已安装里都不显示？
需要像原来的ks固件一样执行一段神秘代码才能显示吗？
（安装包来自：https://github.com/AUK9527/Are-u-ok ）

**Comment by Giter124** [comment]
不用神秘代码，要重启再安装，多试几次应该会成功

**Comment by magicoption** [comment]
安装完了就出现在“服务”一栏里了，没在软件商店界面...这东西不能光明正大出现在软件商店界面

**Comment by jannson** [comment]
必须在服务一栏里面查找。目前所有离线包，我们并没有在软件中心进行管理。以后也许会管理吧，目前还没有做离线包的管理。
