### ISSUE TITLE
samba 共享文件夹打不开

### ISSUE THREAD

**Issue by zheng-jd** [linkease/istoreos#291]
r5s 安装的 istoreos，接在路由器下级作为小主机。samba 配置好电脑能够发现，电脑上也能够账户密码登录成功连接，但是就是打不开共享文件夹
![image](https://user-images.githubusercontent.com/108261457/178102155-0f61594b-9700-4886-8fdd-0326e0338bab.png)

一点共享文件夹就提示
![image](https://user-images.githubusercontent.com/108261457/178102161-23c85b2c-ca4a-467d-84af-e3149a6430d9.png)

Windows，手机都试过，能连接，但是都打不开共享文件夹。

**Comment by jannson** [comment]
用首页快速配置的么？看看首页的配置信息。。。
你可以删除配置，重新配置试试，大概率没问题。不行就周一加群帮你看看。

**Comment by zheng-jd** [comment]
> 大

是的，首页快去配置的。请问怎么删除samba配置

**Comment by zheng-jd** [comment]
> 用首页快速配置的么？看看首页的配置信息。。。
> 
> 你可以删除配置，重新配置试试，大概率没问题。不行就周一加群帮你看看。

你是说删除共享目录的配置吗

**Comment by hai201235** [comment]
我的也是的打不开

**Comment by hai201235** [comment]
![Uploading 09E00F0B-AC67-47E1-B10A-BE303FD96219.jpeg…]()

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3339/1
