### ISSUE TITLE
单线双拨无法使用

### ISSUE THREAD

**Issue by magicoption** [linkease/istoreos#30]
单线双拨启用后，VWAN接口显示“网络配置错误”，无法使用。望修复！

**Comment by jannson** [comment]
目前我没有单线多拨的测试环境，我估计得自己搭建 pppoe-server 服务器才行了。

**Comment by jannson** [comment]
我想起来了，可能需要给 pppoe-server 打补丁，然后加上 macvlan 啥的，等等，下周的版本我们再考虑吧

**Comment by jannson** [comment]
已经加上相关的补丁，支持了 21 版本。貌似 21 版本 macvlan 还不能打勾啥的。里面有相关的提示。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3872/1
