### ISSUE TITLE
求助，手动安装插件后在服务里面找不到啊

### ISSUE THREAD

**Issue by xtwj8888** [linkease/istoreos#301]
离线安装了passwall和bypass，也显示安装成功了，但是在服务里面看不到是咋回事啊

**Comment by My-By** [comment]
是不是安装错版本了？
https://github.com/AUK9527/Are-u-ok

**Comment by xtwj8888** [comment]
哎，安装的是x86的，我的是R4S，搞晕了，现在可以用了，谢谢

**Comment by My-By** [comment]
> 哎，安装的是x86的，我是R4S，搞晕了，现在可以用了，谢谢

小事，我也遇到过。
