### ISSUE TITLE
AMD GX-420CA无法显示温度

### ISSUE THREAD

**Issue by ZrthurFe** [linkease/istoreos#304]
0715版本AMD GX-420CA无法显示温度，不知道会不会有修复计划

**Comment by jannson** [comment]
之前的版本也无法显示的吧？如果之前的版本由显示，我们可以考虑修复。目前我们没机器，有机器我们肯定是可以支持的。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3330/1
