### ISSUE TITLE
能否支持在线/本地安装kmod内核模块

### ISSUE THREAD

**Issue by GreenTeodoro839** [linkease/istoreos#305]
安装kmod提示内核不兼容，这个大佬的固件预置了kmod本地源https://github.com/SuLingGG/OpenWrt-Rpi，希望istoreos也能添加本地kmod源

**Comment by jannson** [comment]
我们是跟随官方的系统，按理 kmod 是可以更新的。不过我们默认 没提供这样的支持，等我们开源的吧，你可以自己编译操作。目前我们暂时不考虑这种 case

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3329/1
