### ISSUE TITLE
homeassistant服务未安装

### ISSUE THREAD

**Issue by Giter124** [linkease/istoreos#31]
X86 安装homeassistant插件后一直是homeassistant服务未安装，按安装按钮也没有响应，已经设置好特殊上网环境

**Comment by jannson** [comment]
收到，我们内部跟着测试下

**Comment by jannson** [comment]
发现问题所在了，我们更新插件中

**Comment by jannson** [comment]
明天软件中心就更新好了。今晚提交上线了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3869/1
