### ISSUE TITLE
提供 socat 插件

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#32]
貌似这个插件方便进行 ipv4/ipv6 的端口转发。

**Comment by flybiubiu** [comment]
有点类似koolshare里的瑞士军刀插件

**Comment by jannson** [comment]
已经增加这个插件。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3866/1
