### ISSUE TITLE
简易的扩容界面

### ISSUE THREAD

**Issue by MeowCold** [linkease/istoreos#34]
简易的扩容界面，指导用户做出合适的操作。
系统扩容
新磁盘挂载

**Comment by jannson** [comment]
新磁盘 挂载 有了啊，目前首页就有个磁盘挂载，如果新硬盘会指导格式化。
对于扩容，目前是提供用户对跟系统新建一个分区，把Docker 安装到新分区。至于跟 文件系统 2G 我感觉空间足够了

**Comment by MeowCold** [comment]
这样啊，我看了下原来是dns问题。我还以为是存储空间不足

**Comment by jannson** [comment]
下个版本，我们首页修复下，如果 DNS 错误，会提示当前 DNS 错误。

**Comment by MeowCold** [comment]
挂载也有点问题，不是报错就是无法挂载成功。用的就是首页的 磁盘信息 那的分区并格式化
感觉时灵时不灵，之后我又从系统，磁盘管理那格式化反倒是自动挂载了。看着有点迷

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3861/1
