### ISSUE TITLE
保存卡页面，ddns无aliyun-ddns，这是现在用的最普遍的吧！

### ISSUE THREAD

**Issue by wssfxtx** [linkease/istoreos#37]
昨天安装好，用了一晚上发现：
1、保存的时候卡界面，例如，关闭ss倒计时到0的时候刷新界面发现还是还是开着的
2、ddns未添加aliyun-ddns，这个应该是目前用的最多的DDNS之一了

**Comment by jannson** [comment]
aliyun-ddns 就是在服务，动态DDNS 里面有的。
保存的时候卡，这个问题我们还没发现，我们试试。

**Comment by oldboyooxx** [comment]
aliyun-ddns 就是在服务，动态DDNS 里面有的。
----
在哪我找半天没找到！

**Comment by jannson** [comment]
看到你回复，我真不好意思。我也发现没有。我们 ARS2 版本是有的，我记混了。我们下下个版本加上。

**Comment by oldboyooxx** [comment]
自己如何手动添加服务商，并且输入服务商的帐号和密码？（ps:ddns 也没看到输入帐号密码的地方）
我现在刷到这个固件，不想退回去了，但是又有阿里云 ddns 的需求，我可以自己折腾，可以给个方向吗？

**Comment by jannson** [comment]
修复了，在服务，DDNS里面，可以选择 aliyun/dnspod.cn 。以后可以考虑放到首页的便捷位置，至少现在肯定是可以了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3853/1
