### ISSUE TITLE
新增迅雷快鸟插件

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#39]
https://github.com/99477204 兄弟提供的建议：

我下载的这个[https://github.com/sensec/luci-app-xlnetacc/releases/tag/v1.0.5.1，但是安装后并不运行。](https://github.com/sensec/luci-app-xlnetacc/releases/tag/v1.0.5.1%EF%BC%8C%E4%BD%86%E6%98%AF%E5%AE%89%E8%A3%85%E5%90%8E%E5%B9%B6%E4%B8%8D%E8%BF%90%E8%A1%8C%E3%80%82)
我之前用的一个openwrt里边的快鸟插件非常稳定，登录后一直没有掉过线，如果可以希望你们研究下提取出来放在软件中心里。因为我从他们公布的插件包里下载的迅雷快鸟安装后，依然是不运行的。附之前用的固件地址，链接:https://www.123pan.com/s/dS5A-By4qd 提取码:SeY7，我之前用的是x86的 4月1号发布的plus大全版。
另外附上他们的GitHub地址https://github.com/sirpdboy/openwrt

**Comment by hyy34** [comment]
请问 帐号登录失败。错误代码: 6，原因: 为了您的帐号安全，请输入图形验证码[6]

这个问题如何解决？


</body>
</html>

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3848/1
