### ISSUE TITLE
希望编译时更新最新的i40e.ko驱动

### ISSUE THREAD

**Issue by longaga** [linkease/istoreos#4]
fw867 制作的openwrt 2.37、2.36 包含新的i40e.ko驱动，可以正确驱动X710T4L 、X710T2L，是目前已知5.4内核唯一的有新驱动的固件，其它5.10内核的固件基本都支持，经测试5.4内核的istoreos固件i40e.ko驱动还是旧版本的。

**Comment by jannson** [comment]
好的，非常感谢。我们将会在下个版本集成。

**Comment by jannson** [comment]
已经支持，请重新测试。

**Comment by longaga** [comment]
> 已经支持，请重新测试。
![164972078-6f5a5641-1a87-4275-ae54-58ff72048bd4](https://user-images.githubusercontent.com/25930270/165502167-8749c38c-eca1-4ec8-8245-66f93ea51b40.png)
已经测试成功，多谢了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3943/1
