### ISSUE TITLE
Samba首页显示的是公网ip?

### ISSUE THREAD

**Issue by Pinehao** [linkease/istoreos#41]
非通过首页配置，访问正常，但是首页显示的是smb://120.193.XXX.XXX（公网IP）/XXXX（目录）

上网环境为独立公网ip的专线，软路由实体机硬盘多余空间挂载的samba

**Comment by jannson** [comment]
应该是现实错误。你路由器拨号的么？这个 IP 显示，仅仅是提供给用户访问的便利，并没有任何实际的配置。哪知道会显示 WAN 口 IP，下下个版本我们看看如何修改

**Comment by Pinehao** [comment]
> 应该是显示错误。你路由器拨号的么？这个 IP 显示，仅仅是提供给用户访问的便利，并没有任何实际的配置。哪知道会显示 WAN 口 IP，下下个版本我们看看如何修改

我是固定ip的专线，显示有问题，实际不影响使用

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3842/1
