### ISSUE TITLE
这个登录名和密码是什么

### ISSUE THREAD

**Issue by penlion** [linkease/istoreos#46]
群晖装了虚拟机里面，点连接后需要修改默认登陆ip，需要输入登陆密码，请问这个登录用户名和密码是什么？
![Uploading 12E909BD-E3BB-421E-8975-727CDAF80AD5.png…]()

**Comment by jannson** [comment]
root

passwall

**Comment by jannson** [comment]
首页 介绍有。

**Comment by penlion** [comment]
> 
首页介绍只有登录192.168.100.1 的 密码password。 没有看到 root的登录名和密码

**Comment by penlion** [comment]
> root
> 
> passwall

![Uploading F90BFF0C-3ACA-49EA-9F9B-EF2D84A50988.jpeg…]()

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3829/1
