### ISSUE TITLE
怎么修改前端登录网址

### ISSUE THREAD

**Issue by penlion** [linkease/istoreos#48]
现在网址是192.168.100.1，不在路由器的网址段，怎么修改istoreos 的网址？

**Comment by jannson** [comment]
是指修改内网 IP 么？最新版本首页有个内网配置，是你想要的么？

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3823/1
