### ISSUE TITLE
保留配置升级到4.22版本固件，提示DNS配置出错

### ISSUE THREAD

**Issue by liyi0820** [linkease/istoreos#49]
旁路由模式，dns为主路由ip。上一版本完全正常。不知道是否与升级时没关闭clash有关

**Comment by jannson** [comment]
DNS 配置错误，是因为你路由器里面的没网络。之前版本也有这个问题，所以我们才加了个 DNS 错误来提示，你需要修改下 DNS，手动设置一个，比如：223.5.5.5 223.6.6.6 都行。

你 DNS 为主路由 IP，但是旁路由，我不知道你关闭了 主路由 的 DHCP，还是旁路由的 DHCP，有的主路由关闭 DHCP 会导致 DNS 也被关闭了。 DNS 错误肯定是路由器里面没网络，连接的设备反而有网络。

**Comment by liyi0820** [comment]
> DNS 配置错误，是因为你路由器里面的没网络。之前版本也有这个问题，所以我们才加了个 DNS 错误来提示，你需要修改下 DNS，手动设置一个，比如：223.5.5.5 223.6.6.6 都行。
> 
> 你 DNS 为主路由 IP，但是旁路由，我不知道你关闭了 主路由 的 DHCP，还是旁路由的 DHCP，有的主路由关闭 DHCP 会导致 DNS 也被关闭了。 DNS 错误肯定是路由器里面没网络，连接的设备反而有网络。

谢谢宝哥。目前DNS DHCP都是放主路由上的。我重置后完全重头设置后就正常了，应该是版本升级的时候出现了什么冲突
