### ISSUE TITLE
新版的首页和网络向导这两个页面都是空白的

### ISSUE THREAD

**Issue by laopana** [linkease/istoreos#5]
用PE完全删除所有分区之后重新安装之后还是空白的
![1](https://user-images.githubusercontent.com/103490639/162911634-30ad3381-7e3d-4a83-bdf9-637b77dcd971.png)
![2](https://user-images.githubusercontent.com/103490639/162911660-f4c056a8-8121-4240-8294-92139ee2163e.png)

**Comment by laopana** [comment]
经过进一步排查发现，使用谷歌浏览器是正常的，但是使用Windows自带的最新版的EDGE（跟谷歌浏览器一样都是Chromium内核的那个）就不显示，建议大佬得空的时候排查一下

**Comment by jannson** [comment]
请清空 EDGE 的缓存试试。之前旧版本有缓存问题。

**Comment by jannson** [comment]
也许跟这个问题相似，目前无法判断你得问题，先关闭了：https://github.com/linkease/istoreos/issues/24

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3940/1
