### ISSUE TITLE
UI 配置界面，有时候卡主不动，非常影响体验

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#54]
如下图所示：

![image](https://user-images.githubusercontent.com/4100344/164896846-245a7e2b-7d93-41ba-9ac7-8120b22c2bd3.png)

**Comment by jannson** [comment]
类似的共性问题有：#40

**Comment by jannson** [comment]
已经修复

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3808/1
