### ISSUE TITLE
希望支持在线安装Kmod内核模块

### ISSUE THREAD

**Issue by pjx11131719** [linkease/istoreos#57]
想安装kmod-ath10k

**Comment by jannson** [comment]
我们有计划通过软件中心支持一些额外的，不是都需要的内核模块。不过现在还有很多其他问题需要集中精力解决，这个优先级还低些。

**Comment by gzsdbb** [comment]
> 

这个 很重要 还是希望能保持官方的内核md5值

**Comment by jannson** [comment]
嗯。明白。。。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3799/1
