### ISSUE TITLE
无法登陆SFTP,SSH可以登陆

### ISSUE THREAD

**Issue by qingenli** [linkease/istoreos#6]
![2022-4-12 20-3-59](https://user-images.githubusercontent.com/30209737/162958686-50415b56-e488-4ee3-8b95-5cb96f40eb6a.png)

**Comment by ziguayungui** [comment]
opkg update

opkg install vsftpd openssh-sftp-server

可以自己安装

**Comment by jannson** [comment]
看来得考虑做成一个插件。

**Comment by jannson** [comment]
已经增加了 SFTP 插件

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3937/1
