### ISSUE TITLE
状态 概览页面温度一直27度！

### ISSUE THREAD

**Issue by zhengyi1314** [linkease/istoreos#61]
如题

**Comment by jannson** [comment]
{result: {temperature: 27}}
result: {temperature: 27}
temperature: 27

还真是，我这边也是。。。估计是要适配下。。。收到

**Comment by molin830** [comment]
没错 cpu温度一直是27度

**Comment by dellffff** [comment]
我也是一直27度。

**Comment by wangweiweiwei** [comment]
me too

**Comment by jannson** [comment]
已经修复，在i最新的版本。

**Comment by caragorn** [comment]
我的是r86s 最新版0609，温度没有显示，为空

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3788/1
