### ISSUE TITLE
（旁路有）用192.168.1.2这个地址 主路由用192.168.1.1

### ISSUE THREAD

**Issue by wanglongfei8899** [linkease/istoreos#62]
iStoreOS（旁路有）用192.168.1.2这个地址  主路由用192.168.1.1这个地址  iStoreOS就有问题不能刷新插件

**Comment by jannson** [comment]
刷新插件？就是插件刷不出来么？来个截图啥的呗。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3786/1
