### ISSUE TITLE
miniupnp有问题的更换版本可以解决。

### ISSUE THREAD

**Issue by lingyunzhiss** [linkease/istoreos#65]
系统自带的MiniUpnp不工作，更换低版本的解决了。
![image](https://user-images.githubusercontent.com/19514184/164990188-30b7cbf6-abe4-4441-b64d-1a1c48c6707c.png)
![image](https://user-images.githubusercontent.com/19514184/164990237-f93a1128-8928-4eca-9860-52523fd29873.png)

**Comment by jannson** [comment]
感谢提供重要的信息，貌似有个用户也反馈过，当时没注意。

**Comment by longaga** [comment]
![_6Z8T)CC8ZH9@9IP60H` H](https://user-images.githubusercontent.com/25930270/165003107-6140b6d5-8792-4b92-95f1-4ed9786fc9be.png)
没有问题吧，勾选启动 UPnP 与 NAT-PMP 服务

**Comment by juzixs** [comment]
我的MiniUpnp也不工作 试试这个降MiniUpnp版本看看有没有效果去

**Comment by jannson** [comment]
找了下，可能跟下面的两个 issue 相关：
https://github.com/openwrt/packages/issues/14145

https://github.com/openwrt/packages/pull/16011

貌似因为你们没公网 IP 导致？

**Comment by syj119** [comment]
没有公网IP是大势所趋，越来越多的人upnp会不能用

**Comment by jannson** [comment]
通过强制转发，可以让 UPNP 生效。目前强制转发已经成为默认配置项，如果是老配置文件，可以考虑自己配置，新刷的固件将会使用默认值。

**Comment by m0eak** [comment]
> 通过强制转发，可以让 UPNP 生效。目前强制转发已经成为默认配置项，如果是老配置文件，可以考虑自己配置，新刷的固件将会使用默认值。

开启强制转发还是不行。。。

**Comment by ray0019** [comment]
> 问题已经确认，有朋友用一下老版本才能解决：
> 
> ![50359d9579bf1a914ba0af81d3fe2c6](https://user-images.githubusercontent.com/4100344/165934810-bc885762-1fb6-45b8-bff7-f996c688ff3e.png)

请问去哪里下载老版本的，最新0331版的固件自带的upnp还是无法启动。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3778/1
