### ISSUE TITLE
iStoreOS这么高大上，端口转发都没有吗？

### ISSUE THREAD

**Issue by niceran** [linkease/istoreos#78]
iStoreOS这么高大上，端口转发都没有吗？
找个几个钟都没有找到，是真的没有吗？
有公网IP没有这个，没法玩了

**Comment by yaoshuangshl** [comment]
这个有啊

**Comment by niceran** [comment]
> 这个有啊

在哪个菜单里？我安装最新的4.23的，没找到

**Comment by niceran** [comment]
> > 这个有啊
> 
> 在哪个菜单里？我安装最新的4.23的，没找到

解决了，更新商店，安装socat

**Comment by jannson** [comment]
防火墙也可以做端口转发的

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3742/1
