### ISSUE TITLE
备份问题

### ISSUE THREAD

**Issue by gzsdbb** [linkease/istoreos#8]
现在 最大的问题是应用中心的备份问题 有些离线安装的插件 不能显示在应用中心里
 备份的同时也不会备份出来 
那问题来了 以后要是升级 这些插件就要重装再装一次了 !
虽然 配置文件还在!重装安装一次也没什么 
毕竟有时候固件内核的更新 也有可能会让这些插件失效
 所以 最终的解决办法还丰富应用中心的插件数量!

**Comment by jannson** [comment]
有个本地备份，是可以支持所有插件的备份的。那个轻量备份只能备份软件中心安装的插件。。。
