### ISSUE TITLE
提供 USB 引导之后，写入路由器里面的硬盘系统的功能（相当于快速从 U 盘安装系统）

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#82]

**Comment by genesis-lua** [comment]
大佬，其实用Ubuntu的安装盘安装openwrt非常的方便，网上那些方法都太负责，先制作一个ubuntu安装启动盘，进去之后try ubuntu，然后选到对应的img右键写入器写道对应的盘，全程5分钟

**Comment by shural** [comment]
如果像openwrt那样release generic-ext4-combined...的img，直接dd写就好了。

**Comment by genesis-lua** [comment]
> 如果像openwrt那样release generic-ext4-combined...的img，直接dd写就好了。

我原来也是DD写的，后来发现用写入器更方便，图形界面操作更适合新手

**Comment by jannson** [comment]
我也都是 dd，但是得先启动进入系统，然后再 dd 安装，就行了。非常快。但是 很多用户不会用 dd 命令，所以我想做个界面的功能，让用户在界面点击，就行了。

**Comment by jannson** [comment]
此功能已经在最新的固件上支持，直接在命令行向导中完成。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3730/1
