### ISSUE TITLE
考虑先开发一个更好的导航页面，来暂时代替狗皮肤

### ISSUE THREAD

**Issue by jannson** [linkease/istoreos#83]
随着 docker 应用的增加，好多应用都是一个独立的端口，有个快速导航的入口很重要，可以参考群晖的 webstation：

同时有一些插件（Ubuntu，Jellyfin，Aria2 等等），可以让用户添加端口到导航入口。

![image](https://user-images.githubusercontent.com/4100344/165728221-f2a28e3f-a433-4fec-b99f-1e235c235114.png)

**Comment by jannson** [comment]
![image](https://user-images.githubusercontent.com/4100344/175439816-f9a197dc-d6da-4e41-97a7-ec4a34fb8480.png)

**Comment by jannson** [comment]
暂时完成，叫 istorex

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3728/1
