### ISSUE TITLE
Passwall插件适配问题

### ISSUE THREAD

**Issue by terrywusc** [linkease/istoreos#84]
使用20220422版本iStoreOS，应用商店 v0.1.9-5，最新Passwall安装脚本（更新于20220425），使用ESXi 6.7u3虚拟机。使用过程中出现如下问题：
1. （v20220429已修复）在Passwall插件内保存并应用设置时，30秒倒计时内不提示成功，等待到0秒后刷新浏览器，右上角提示未保存设置，手动保存才生效。怀疑UI的bug。
2. 在Passwall或VSSR规则列表内添加/修改/删除直连域名后，点击保存并应用，提示没有待应用的更改。同疑UI Bug。
3. 在手动重启Passwall或VSSR或iStoreOS后，Passwall规则列表内的直连规则不生效，还是走代理。

**Comment by jannson** [comment]
对，UI 有个非常烦人的 BUG，就是更新之后读秒，然后一直读到0。今天晚上更新的版本，请再试试。谢谢。。。

**Comment by wildtigerw** [comment]
之前qbittorrent也有类似问题。

**Comment by woann** [comment]
这个问题到现在也没有解决，就是文本框的内容修改了，提交会提示“没有待应用的更改”，就是压根没监听文本框的内容变更。其他的op固件不存在这个问题，就istoreos有这个问题
