### ISSUE TITLE
网络-接口刷新不出来

### ISSUE THREAD

**Issue by wanglongfei8899** [linkease/istoreos#86]
![image](https://user-images.githubusercontent.com/75508757/165764474-de7b31a7-34c8-42b6-925e-1e891797babe.png)

**Comment by jannson** [comment]
一直刷不出来，还是偶尔性质？重启 再试试呢？

**Comment by wanglongfei8899** [comment]
更新固件好了

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3720/1
