### ISSUE TITLE
网页进不去了

### ISSUE THREAD

**Issue by neracn** [linkease/istoreos#87]
我转成VMDK，用esxi虚拟以后，第一次进入设置好后，网页就进不去了，一片白屏。网络正常，SSH也能进。 请问这是怎么回事呢？
设置的是旁路由模式

**Comment by neracn** [comment]
![微信截图_20220428222019](https://user-images.githubusercontent.com/32286995/165774014-f5feda45-c4b8-4422-b91b-808c833167ef.png)
退出再进又不行了。。。

**Comment by jannson** [comment]
是最新版本的固件么？我记得我们修复了 argon 主题的错误，导致网页进不去的问题。如果是最新版本，则可以加群找我，我远程帮你看看。浏览器 F12 可以在网页 Network 看出一些错误

**Comment by neracn** [comment]
宝大好！
我这台虚拟的istoreos是上个周末新装的，我记得直接在koolcenter上直接下载的0422版。
我已申请加入istoreos群，正在等待验证。
谢谢

**Comment by neracn** [comment]
宝大好！
今天傍晚突然又能进了一次。进去看了下版本号，是0422的。赶紧趁着能进入，在线刷了0429。
截至目前，都可以正常进入了。
谢谢！

**Comment by jannson** [comment]
这个问题先关闭。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3717/1
