### ISSUE TITLE
应用安装失败

### ISSUE THREAD

**Issue by DuYaoCheng** [linkease/istoreos#9]
J1900物理机安装，内存4G，硬盘32G。
可道云、Jellyfin安装失败。Aria2无法启动，首页的“存储服务”快速配置、“DNS配置”点击没反应。
![image](https://user-images.githubusercontent.com/103754281/163578423-952da240-0969-4c34-a4cb-d3d0608120f8.png)

**Comment by jannson** [comment]
Aria2 肯定无法启动，你在首页配置试试，可能你的文件夹没创建好。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3931/1
