### ISSUE TITLE
请支持 cifs 插件，支持 Samba 跟 webdav 的挂载能力

### ISSUE THREAD

**Issue by genesis-lua** [linkease/istoreos#91]
最近尝试了istore固件，有些小问题反馈一下：
1、m.2安装的系统，同时主机有一个固态和一个硬盘，开机时会显示找不到boot文件的，进入grub修改set root=（hdx，gptx）才能进入
2、急需挂载局域网nas的cifs插件，因为openwrt的smb能力有限，更多的影视资源都存在其他nas
3、系统原生的软件包管理其实蛮好用，能否在编译固件时尽可能收集常用package一同编译？

**Comment by genesis-lua** [comment]
https://github.com/kenzok8/openwrt-packages

**Comment by genesis-lua** [comment]
kiddin软件库中的cifs插件可用，已经成功挂载nas
[luci-app-cifs-mount_git-22.112.23484-481c218_all.zip](https://github.com/linkease/istoreos/files/8590267/luci-app-cifs-mount_git-22.112.23484-481c218_all.zip)
需要的可以试试

**Comment by jannson** [comment]
嗯，好的。非常感谢。这个 issue 太体贴了。今晚上更新的版本肯定来不及了。下个版本吧。

**Comment by jannson** [comment]
Grub 问题同 https://github.com/linkease/istoreos/issues/81

**Comment by jannson** [comment]
昨天的版本已经支持网络文件系统的挂载。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3706/1
