### ISSUE TITLE
应用商店-维护-本地备份疑似无法备份手动安装的应用

### ISSUE THREAD

**Issue by genesis-lua** [linkease/istoreos#93]
大佬，最新的升级通过本地备份（可以离线那个）只能还原到应用商店里面有的应用，第三方应用没有自动还原，不知道4月29的固件是不是有同样问题，从4月22固件升级上来的

**Comment by wildtigerw** [comment]
我已升级，还是这样。

**Comment by jannson** [comment]
通过本地备份也不行？那这个就是备份插件的 BUG 了。这个我们先放到待确认的问题里面。

**Comment by genesis-lua** [comment]
> 通过本地备份也不行？那这个就是备份插件的 BUG 了。这个我们先放到待确认的问题里面。
> 
> 本地备份，是备份到磁盘里面的，不是在线更新的。

对的，是备份到本地的
![image](https://user-images.githubusercontent.com/26401920/166889121-d3d36cc7-15de-4bf7-8b83-ee1751ff818a.png)

**Comment by jannson** [comment]
对，问题确实存在。我们得考虑这个备份能支持离线包的备份。。。

**Comment by jannson** [comment]
最新版本升级插件之后，插件不会丢失。同时有沙箱模式，可以保证方便的恢复到上个系统版本。那么这个 issue，插件备份则已经不再是核心的问题，先关闭了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3701/1
