### ISSUE TITLE
在线更新版本后，所有应用商店安装应用的全丢失

### ISSUE THREAD

**Issue by papersnake** [linkease/istoreos#94]
看到一个更新的红点，会快生级成功
但是应用商店安装的所有应用全部没有了，包括手动安装的，都没有了，
不家挂载点里有两个变成不存在了，但是系统不受影响
![QQ五笔截图未命名](https://user-images.githubusercontent.com/455729/166102052-104f64ed-0ef4-4107-936b-4575397dc4d7.png)

**Comment by wildtigerw** [comment]
应用需要在升级前手动备份，第一版发布的时候就说过了。

**Comment by jannson** [comment]
楼上正解，我们后续必须会支持到升级插件不丢的能力。现在暂时还不行。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3698/1
