### ISSUE TITLE
hyper-v 虚拟机扩容 空间不成功

### ISSUE THREAD

**Issue by pang1986267** [linkease/istoreos#96]
由于 空间问题，安装插件提示空间不足，想扩展一下储存空间和根目录空间，看了下原来的只有2G空间，想扩展到20G，新建的磁盘一直挂载不出来。用的IMG文件转的 hyper 磁盘

**Comment by pang1986267** [comment]
问题已解决，不能挂载根目录，只能挂载到/opt/docker

**Comment by pang1986267** [comment]
是

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3695/1
