### ISSUE TITLE
iStore安装软件报255错误

### ISSUE THREAD

**Issue by milhu** [linkease/istoreos#97]
离线安装或者是直接安装iStore里面的软件，都报255的错误。主机是R86s，直接物理机下刷入iStoreOS 0429的版本

**Comment by milhu** [comment]
Collected errors:
 * verify_pkg_installable: Only have 0kb available on filesystem /overlay, pkg app-meta-ddnsto needs 6
 * opkg_install_cmd: Cannot install package app-meta-ddnsto.

**Comment by ziguayungui** [comment]
overlay 分区没空间了，检查一下磁盘使用情况。

**Comment by milhu** [comment]
嗯，已经解决，不知道安装的时候出了什么问题，重新的安装一遍，又重新挂载所有的分区，就解决了。多谢

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3693/1
