### ISSUE TITLE
动态DNS阿里云配置成功后，重启就报错

### ISSUE THREAD

**Issue by RichKyle** [linkease/istoreos#99]
132445       : https://alidns.aliyuncs.com/?Action=AddDomainRecord&DomainName=top&RR=（域名）&Type=A&Value=（我的ip）&Format=JSON&TTL=600&Version=2015-01-09&AccessKeyId=（我的id）&SignatureMethod=HMAC-SHA1&Timestamp=2022-05-02T05%3A24%3A45Z&SignatureVersion=1.0&SignatureNonce=a67f77df-6c39-4cce-91c6-b5d7c61e9a8f&Signature=9hxo7vhgsy6ZqVZavk44wy7DUsY%3D:
2022-05-02 13:24:45 ERROR 400: Bad Request.

**Comment by jannson** [comment]
我先放到待确认问题里面。我们先确认下

**Comment by fencatn** [comment]
这个报错是时间戳不对，检查下路由器时间呢

**Comment by RichKyle** [comment]
> 这个报错是时间戳不对，检查下路由器时间呢

时间没有问题

**Comment by jannson** [comment]
最新版本我已经亲手帮好几个人配置成功了。

**Comment by kc-bao** [comment]
此问题已在 **酷友社** 上被提及。那里可能有相关详细信息：

https://www.koolcenter.com/t/topic/3688/1
